import { LandingSectionContent } from "./landingContent";

export const defaultAboutSections: LandingSectionContent[] = [
  {
    key: "about-hero",
    name: "AboutHero",
    enabled: true,
    eyebrow: "ABOUT US",
    titlePrimary: "BHARAT ORGANIC",
    titleSecondary: "EXPO 2027",
    subtitle: "Our Mission & Vision",
    description: "Discover the driving force behind Bharat Organic Expo. We are committed to fostering sustainable practices, nurturing conscious communities, and elevating India's organic industry to global standards.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    imageAlt: "Bharat Organic Expo 2027 exhibition and visitors",
    secondaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    buttonLabel: "REGISTER AS A VISITOR",
    buttonHref: "/registration/visitor-registration",
    secondaryButtonLabel: "BOOK YOUR STALL",
    secondaryButtonHref: "/registration/book-a-stand",
  },
  {
    key: "about-strip",
    name: "AboutStrip",
    enabled: true,
    title: "KEY STATS & HIGHLIGHTS",
    items: [
      { title: "EXPERIENCE THAT MATTERS", subtitle: "Decades of collective leadership across sectors", icon: "Users" },
      { title: "INSIGHTS THAT SHAPE", subtitle: "Actionable perspectives for industry advancement", icon: "Target" },
      { title: "NETWORKS THAT CONNECT", subtitle: "Strong national & global partnerships", icon: "Globe" },
      { title: "MENTORSHIP THAT EMPOWERS", subtitle: "Guiding the next generation of changemakers", icon: "TrendingUp" },
    ],
  },
  {
    key: "home-about",
    name: "HomeAbout (Who We Are)",
    enabled: true,
    eyebrow: "ABOUT ORGANIC EXPO",
    title: "WHO WE ARE",
    description: "Bharat Organic Expo 2027 is India's premier international exhibition and conference dedicated to organic farming, natural healthcare, Ayurveda, and eco-friendly living. Our main objective is to bring together farmers, organic producers, wellness brands, trade buyers, and industry experts onto one common platform to promote a healthy and sustainable lifestyle across the globe.",
    secondaryDescription: "As a comprehensive platform for organic agriculture and natural wellness, we connect grassroots farmers and eco-friendly innovators directly with large wholesale buyers, grocery store chains, exporters, and investors. We aim to help organic producers expand their market reach, introduce innovative natural products, and create genuine business opportunities for local producers on a global stage.",
    bottomStatement: "Every year, thousands of passionate visitors, business owners, healthcare experts, and visionary investors gather at our event. They participate in interactive discussions, discover the latest market trends, and form strong business partnerships to actively support organic farming, protect the environment, and build a cleaner, greener, and healthier future for everyone.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    imageAlt: "Bharat Organic Expo - Who We Are",
    secondaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
  },
  {
    key: "event-overview",
    name: "EventOverview",
    enabled: true,
    eyebrow: "EVENT OVERVIEW",
    title: "A Global Platform Connecting Healthcare, Wellness & Business Opportunities",
    description: "Bharat Organic Expo 2027 stands as India's most influential international platform dedicated to organic excellence, wellness innovation, and sustainable living. Entering its prestigious edition, the Expo represents a strategic evolution—from a conventional trade exhibition into a powerful global ecosystem for business growth, policy exchange, knowledge sharing, and international collaboration.",
    secondaryDescription: "With a strong legacy of 10+ years and 8 successfully executed editions, the Expo has established itself as a trusted meeting ground for organic leaders, wellness brands, sustainable technology providers, investors, policymakers, researchers, startups, and global delegations from across the world.",
    date: "19th – 21st February 2027",
    location: "New Delhi",
    rightTitle: "KEY SECTORS",
    items: [
      { label: "Healthcare & Medical Industry", value: "#3b82f6", icon: "HeartPulse" },
      { label: "AYUSH & Traditional Medicine", value: "#22c55e", icon: "Sprout" },
      { label: "Wellness, Fitness & Lifestyle", value: "#f59e0b", icon: "User" },
      { label: "Digital Health, AI & MedTech", value: "#8b5cf6", icon: "Monitor" },
      { label: "Medical Tourism in India", value: "#06b6d4", icon: "Plane" },
      { label: "Nutrition, Organic & Sustainable Living", value: "#10b981", icon: "Leaf" },
    ],
  },
  {
    key: "about-organizer",
    name: "AboutOrganizer",
    enabled: true,
    eyebrow: "ABOUT THE ORGANIZER",
    title: "NAMO GANGE WELLNESS PVT. LTD.",
    subtitle: "OUR JOURNEY & FLAGSHIP EVENTS — A LEGACY OF GROWTH & INNOVATION",
    description: "A professionally managed exhibition and conference organizer in India, specializing in creating large-scale B2B trade shows, healthcare exhibitions, and global business platforms.",
    secondaryDescription: "Established in 2016, the company has built a strong reputation for delivering high-impact, result-driven platforms that combine exhibitions, conferences, buyer–seller meets, and Indian participation into one ecosystem.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    imageAlt: "Namo Gange Wellness Pvt. Ltd.",
    logoImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    secondaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    value: "10+ YEARS OF EXCELLENCE",
    items: [
      { title: "Indian exhibitions & trade shows", description: "Creating large-scale B2B trade shows and global business platforms." },
      { title: "Healthcare conferences & seminars", description: "Expert-led panels and knowledge sharing summits." },
      { title: "Buyer–Seller Meets (B2B matchmaking)", description: "Direct pre-scheduled business interactions." },
      { title: "Sponsorship & brand partnerships", description: "High-impact brand visibility and sponsorship packages." },
      { title: "Indian collaborations & delegations", description: "Connecting national delegations and industry partners." },
      { title: "Punjab Health & Wellness Expo", description: "Flagship regional healthcare expo." },
      { title: "The Yogshala Expo", description: "India's premier yoga and wellness event." },
      { title: "Organic Expo", description: "Leading international trade show for organic products." },
    ],
  },
  {
    key: "vision-mission",
    name: "VisionMission",
    enabled: true,
    eyebrow: "OUR GUIDING PRINCIPLES",
    title: "OUR VISION & MISSION",
    subtitle: "Pioneering the future of organic agriculture, sustainable wellness, and global commerce",
    items: [
      {
        title: "OUR VISION",
        subtitle: "India as a Global Wellness Hub",
        description: "To position India as a Global Hub for Healthcare, Wellness, and AYUSH, by creating an integrated ecosystem that connects traditional wisdom, modern healthcare, innovation, and global markets. We envision a future where preventive healthcare, holistic wellness, and sustainable living are at the core of global development.",
        icon: "Eye",
      },
      {
        title: "OUR MISSION",
        subtitle: "World-Class B2B Health Platform",
        description: "To build a world-class B2B healthcare and wellness platform that brings together industry leaders, innovators, buyers, and global stakeholders to drive business growth and collaboration. We aim to promote preventive healthcare, AYUSH, digital health, and wellness innovation.",
        icon: "Target",
      },
    ],
  },
  {
    key: "four-pillars",
    name: "FourPillars",
    enabled: true,
    eyebrow: "OUR FOUNDATION",
    title: "ONE PLATFORM. FOUR POWERFUL PILLARS.",
    subtitle: "Built upon core principles that drive impact, trust, and sustainable industry transformation",
    items: [
      {
        title: "INTERNATIONAL EXHIBITION",
        subtitle: "40,000+ sq ft across three halls",
        description: "Spanning 40,000+ sq ft across three halls, featuring 200+ exhibitors from 8 key sectors including Medical, AYUSH, Wellness, and Digital Health. Witness live demos, finalize deals, and explore global innovations in dedicated country pavilions for specialized high-level networking and business growth.",
        image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
        icon: "Globe",
      },
      {
        title: "CONFERENCE & KNOWLEDGE SUMMIT",
        subtitle: "30+ sessions over 3 days",
        description: "The 18th Edition, Arogya Sangoshthi, offers 30+ insightful sessions over 3 days, with 150+ distinguished speakers including government officials and industry CEOs. Explore critical discussions across 6 thematic tracks, attracting 2,000+ delegates for knowledge exchange and policy dialogue.",
        image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
        icon: "GraduationCap",
      },
      {
        title: "GLOBAL EXCELLENCE AWARDS",
        subtitle: "Prestigious recognition ceremony",
        description: "Our prestigious 3rd Edition program, a formal evening ceremony on Day 2, recognizes ground breaking achievements and fosters brand authority. Categories include Best Healthcare Innovation, Excellence in AYUSH, and Wellness Entrepreneur of the Year, acknowledging pioneering start ups and influential industry leaders.",
        image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
        icon: "Trophy",
      },
      {
        title: "B2B BUYER-SELLER MEET",
        subtitle: "Pre-scheduled 1-on-1 meetings",
        description: "Designed to forge powerful partnerships and drive global commerce, this pillar facilitates pre-scheduled 1-on-1 meetings within dedicated business lounges. We host international buyer delegations from key markets, offering professional matchmaking services with a target of 500+ impactful B2B meetings.",
        image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
        icon: "Handshake",
      },
    ],
  },
  {
    key: "about-venue",
    name: "AboutVenue",
    enabled: true,
    eyebrow: "OUR VENUE",
    title: "Why Pragati Maidan, New Delhi?",
    subtitle: "Pragati Maidan, New Delhi — Heart of India's Trade & Commerce",
    description: "Located in the heart of New Delhi, Pragati Maidan is India's premier exhibition complex offering state-of-the-art halls, seamless metro accessibility, and world-class hospitality infrastructure.",
    location: "Pragati Maidan, New Delhi",
    date: "19th – 21st February 2027",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    imageAlt: "Pragati Maidan Exhibition Centre",
    secondaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    buttonLabel: "GET DIRECTIONS ON GOOGLE MAPS",
    buttonHref: "https://maps.google.com",
    items: [
      { title: "International Venue", description: "India's premier international exhibition & convention venue with world-class facilities" },
      { title: "Excellent Connectivity", description: "Excellent connectivity via dedicated Metro, International Airport & Central Delhi hubs" },
      { title: "Modern Infrastructure", description: "State-of-the-art infrastructure featuring modern air-conditioned exhibition hall space" },
      { title: "Global Destination", description: "Preferred global destination for high-profile trade fairs, congresses & mega exhibitions" },
      { title: "Strategic Location", description: "Strategically located close to key government ministries, foreign embassies & institutions" },
      { title: "Business Environment", description: "A perfect business-centric environment designed for global networking & deal-making" },
    ],
  },
  {
    key: "about-faq",
    name: "AboutFaq",
    enabled: true,
    eyebrow: "SUPPORT & INFO",
    title: "Frequently Asked Questions",
    subtitle: "Find answers to common inquiries about the Bharat Organic Expo 2027.",
    quote: "Still have questions about exhibiting at the Expo?",
    buttonLabel: "CONTACT OUR HELP DESK",
    buttonHref: "/contact",
    bannerTitle: "Be Part of India's Global Organic Movement",
    bannerSubtitle: "Ignite Your Growth",
    bannerFeature: "Exhibit. Connect. Collaborate. Grow. Join industry leaders, buyers, innovators and organic brands shaping a healthier, sustainable future.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    secondaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    items: [
      { title: "What is the Bharat Organic Expo 2027?", description: "It is India's premier international exhibition & conference dedicated to organic products, natural healthcare, Ayurveda, and sustainable living solutions under one integrated platform." },
      { title: "Who should attend this expo?", description: "Organic farmers, wholesale buyers, retailers, distributors, wellness entrepreneurs, policymakers, and international trade delegations looking to discover authentic organic products and build global partnerships." },
      { title: "What are the key highlights of the expo?", description: "The event features a large international exhibition pavilion, technical knowledge conferences, B2B buyer-seller meets, and prestigious industry excellence recognition programs." },
      { title: "What industries are covered in the expo?", description: "Key sectors include Certified Organic Foods, Natural Herbal Healthcare, Ayurveda, Organic Farming Inputs, Eco-Friendly Packaging, and Sustainable Agriculture Technologies." },
      { title: "How can I participate in the expo?", description: "You can register as an exhibitor, visitor, B2B buyer, or conference delegate directly on our website or by getting in touch with our event help desk." },
    ],
  },
];
