import { LandingSectionContent } from "./landingContent";

export const defaultAboutSections: LandingSectionContent[] = [
  {
    key: "about-hero",
    name: "AboutHero",
    enabled: true,
    eyebrow: "ABOUT US",
    titlePrimary: "BHARAT ORGANIC",
    titleSecondary: "EXPO 2027",
    subtitle: "Our Mission & Vision",
    description: "Discover the driving force behind Bharat Organic Expo. We are committed to fostering sustainable practices, nurturing conscious communities, and elevating India's organic industry to global standards.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    imageAlt: "Bharat Organic Expo 2027 exhibition and visitors",
    secondaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    buttonLabel: "REGISTER AS A VISITOR",
    buttonHref: "/registration/visitor-registration",
    secondaryButtonLabel: "BOOK YOUR STALL",
    secondaryButtonHref: "/registration/book-a-stand",
  },
  {
    key: "about-strip",
    name: "AboutStrip",
    enabled: true,
    title: "KEY STATS & HIGHLIGHTS",
    items: [
      { title: "EXPERIENCE THAT MATTERS", subtitle: "Decades of collective leadership across sectors", icon: "Users" },
      { title: "INSIGHTS THAT SHAPE", subtitle: "Actionable perspectives for industry advancement", icon: "Target" },
      { title: "NETWORKS THAT CONNECT", subtitle: "Strong national & global partnerships", icon: "Globe" },
      { title: "MENTORSHIP THAT EMPOWERS", subtitle: "Guiding the next generation of changemakers", icon: "TrendingUp" },
    ],
  },
  {
    key: "home-about",
    name: "HomeAbout (Who We Are)",
    enabled: true,
    eyebrow: "ABOUT ORGANIC EXPO",
    title: "WHO WE ARE",
    description: "Bharat Organic Expo 2027 is India's premier international exhibition and conference dedicated to organic farming, natural healthcare, Ayurveda, and eco-friendly living. Our main objective is to bring together farmers, organic producers, wellness brands, trade buyers, and industry experts onto one common platform to promote a healthy and sustainable lifestyle across the globe.",
    secondaryDescription: "As a comprehensive platform for organic agriculture and natural wellness, we connect grassroots farmers and eco-friendly innovators directly with large wholesale buyers, grocery store chains, exporters, and investors.",
    bottomStatement: "Every year, thousands of passionate visitors, business owners, healthcare experts, and visionary investors gather at our event to support organic farming and protect the environment.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    imageAlt: "Bharat Organic Expo - Who We Are",
    secondaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
  },
  {
    key: "event-overview",
    name: "EventOverview",
    enabled: true,
    eyebrow: "EVENT OVERVIEW",
    title: "A Global Platform Connecting Healthcare, Wellness & Business Opportunities",
    description: "Bharat Organic Expo 2027 stands as India's most influential international platform dedicated to organic excellence, wellness innovation, and sustainable living.",
    secondaryDescription: "With a strong legacy of 10+ years and 8 successfully executed editions, the Expo has established itself as a trusted meeting ground for organic leaders.",
    date: "19th – 21st February 2027",
    location: "New Delhi",
    rightTitle: "KEY SECTORS",
    items: [
      { label: "Healthcare & Medical Industry", value: "#3b82f6", icon: "HeartPulse" },
      { label: "AYUSH & Traditional Medicine", value: "#22c55e", icon: "Sprout" },
      { label: "Wellness, Fitness & Lifestyle", value: "#f59e0b", icon: "User" },
      { label: "Digital Health, AI & MedTech", value: "#8b5cf6", icon: "Monitor" },
      { label: "Medical Tourism in India", value: "#06b6d4", icon: "Plane" },
      { label: "Nutrition, Organic & Sustainable Living", value: "#10b981", icon: "Leaf" },
    ],
  },
  {
    key: "about-organizer",
    name: "AboutOrganizer",
    enabled: true,
    eyebrow: "ABOUT THE ORGANIZER",
    title: "NAMO GANGE WELLNESS PVT. LTD.",
    subtitle: "OUR JOURNEY & FLAGSHIP EVENTS — A LEGACY OF GROWTH & INNOVATION",
    description: "A professionally managed exhibition and conference organizer in India, specializing in creating large-scale B2B trade shows, healthcare exhibitions, and global business platforms.",
    secondaryDescription: "Established in 2016, the company has built a strong reputation for delivering high-impact, result-driven platforms that combine exhibitions, conferences, buyer–seller meets, and Indian participation into one ecosystem.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    imageAlt: "Namo Gange Wellness Pvt. Ltd.",
    logoImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    secondaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    value: "10+ YEARS OF EXCELLENCE",
    items: [
      { title: "Indian exhibitions & trade shows", description: "Creating large-scale B2B trade shows and global business platforms." },
      { title: "Healthcare conferences & seminars", description: "Expert-led panels and knowledge sharing summits." },
      { title: "Buyer–Seller Meets (B2B matchmaking)", description: "Direct pre-scheduled business interactions." },
      { title: "Sponsorship & brand partnerships", description: "High-impact brand visibility and sponsorship packages." },
      { title: "Punjab Health & Wellness Expo", description: "Flagship regional healthcare expo." },
      { title: "The Yogshala Expo", description: "India's premier yoga and wellness event." },
      { title: "Organic Expo", description: "Leading international trade show for organic products." },
    ],
  },
  {
    key: "vision-mission",
    name: "VisionMission",
    enabled: true,
    eyebrow: "OUR GUIDING PRINCIPLES",
    title: "VISION, MISSION & CORE VALUES",
    subtitle: "Pioneering the future of organic agriculture, sustainable wellness, and global commerce",
    items: [
      {
        title: "OUR VISION",
        subtitle: "A World Flourishing on Organic & Sustainable Excellence",
        description: "To become the premier global ecosystem connecting organic producers, conscious consumers, and sustainable businesses—driving health, economic growth, and environmental stewardship across nations.",
        icon: "Eye",
      },
      {
        title: "OUR MISSION",
        subtitle: "Empowering Growth, Innovation & Conscious Living",
        description: "To empower organic farmers and eco-friendly enterprises through world-class B2B exhibitions, trade conferences, market expansion initiatives, and consumer awareness programs.",
        icon: "Target",
      },
    ],
  },
  {
    key: "four-pillars",
    name: "FourPillars",
    enabled: true,
    eyebrow: "OUR FOUNDATION",
    title: "THE FOUR PILLARS OF OUR EVENT",
    subtitle: "Built upon core principles that drive impact, trust, and sustainable industry transformation",
    items: [
      {
        title: "AUTHENTICITY & CERTIFICATION",
        subtitle: "100% Verified Organic Standards",
        description: "Every exhibitor and product showcase adheres strictly to recognized organic certification standards, building absolute buyer confidence and market trust.",
        image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
        icon: "ShieldCheck",
      },
      {
        title: "MARKET CONNECTIVITY",
        subtitle: "Direct B2B & Global Trade Access",
        description: "Creating direct, high-value trade channels linking rural organic producers and innovative brands with global buyers, retailers, and institutional procurement teams.",
        image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
        icon: "TrendingUp",
      },
      {
        title: "KNOWLEDGE & INNOVATION",
        subtitle: "Expert Conferences & Technical Sessions",
        description: "Fostering industry thought-leadership through technical workshops, policy discussions, sustainable farming innovations, and market trend forecasts.",
        image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
        icon: "BookOpen",
      },
      {
        title: "SUSTAINABILITY & WELLNESS",
        subtitle: "Nurturing Planet & Human Health",
        description: "Promoting chemical-free living, eco-friendly packaging, soil regeneration, and holistic health practices for long-term ecological balance.",
        image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
        icon: "HeartHandshake",
      },
    ],
  },
  {
    key: "about-venue",
    name: "AboutVenue",
    enabled: true,
    eyebrow: "VENUE & LOCATION",
    title: "WORLD-CLASS EXHIBITION CENTER",
    subtitle: "Pragati Maidan, New Delhi — Heart of India's Trade & Commerce",
    description: "Located in the heart of New Delhi, Pragati Maidan is India's premier exhibition complex offering state-of-the-art halls, seamless metro accessibility, and world-class hospitality infrastructure.",
    location: "Pragati Maidan, Mathura Road, New Delhi, Delhi 110001",
    date: "19th – 21st February 2027",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    imageAlt: "Pragati Maidan Exhibition Centre",
    secondaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    buttonLabel: "GET DIRECTIONS ON GOOGLE MAPS",
    buttonHref: "https://maps.google.com",
  },
  {
    key: "about-faq",
    name: "AboutFaq",
    enabled: true,
    eyebrow: "FREQUENTLY ASKED QUESTIONS",
    title: "EVERYTHING YOU NEED TO KNOW ABOUT BHARAT ORGANIC EXPO",
    subtitle: "Find quick answers to common inquiries about exhibiting, visiting, and participating",
    quote: "Still have questions about exhibiting at the Expo?",
    buttonLabel: "CONTACT OUR HELP DESK",
    buttonHref: "/contact",
    bannerTitle: "Be Part of India's Global Organic Movement",
    bannerSubtitle: "Ignite Your Growth",
    bannerFeature: "Exhibit. Connect. Collaborate. Grow. Join industry leaders, buyers, innovators and organic brands shaping a healthier, sustainable future.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    secondaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    items: [
      { title: "What is the Bharat Organic Expo 2027?", description: "It is India's premier international exhibition & conference dedicated to organic products, natural healthcare, Ayurveda, and sustainable living solutions." },
      { title: "Who should attend this expo?", description: "Organic farmers, wholesale buyers, retailers, distributors, wellness entrepreneurs, policymakers, and international trade delegations." },
      { title: "What are the key highlights of the expo?", description: "Large international exhibition pavilion, technical knowledge conferences, B2B buyer-seller meets, and prestigious industry awards." },
      { title: "What industries are covered in the expo?", description: "Certified Organic Foods, Natural Herbal Healthcare, Ayurveda, Organic Farming Inputs, Eco-Friendly Packaging, and Sustainable Agriculture Technologies." },
      { title: "How can I participate in the expo?", description: "Register as an exhibitor, visitor, B2B buyer, or conference delegate directly on our website." },
    ],
  },
];
