import { LandingSectionContent } from "./landingContent";

export const defaultAdvisorySections: LandingSectionContent[] = [
  {
    key: "advisory-hero",
    name: "AdvisoryHero",
    enabled: true,
    eyebrow: "GUIDING. INSPIRING. TRANSFORMING.",
    titlePrimary: "ADVISORY",
    titleSecondary: "BOARD MEMBERS",
    subtitle: "Strategic Guidance & Industry Leadership",
    description: "Our Advisory Board comprises distinguished leaders, industry experts, and visionaries who bring strategic guidance, deep expertise and a shared commitment to drive Bharat Organic Expo towards a sustainable, innovative and impactful future.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    imageAlt: "Bharat Organic Expo Advisory Board",
    secondaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    items: [
      { title: "LEADING VISIONARIES", subtitle: "From diverse organic industries", icon: "Users" },
      { title: "STRATEGIC GUIDANCE", subtitle: "For sustainable business growth", icon: "Award" },
      { title: "INDUSTRY EXPERTISE", subtitle: "Driving innovation & green impact", icon: "Lightbulb" },
      { title: "COLLABORATIVE LEADERSHIP", subtitle: "Building a stronger organic ecosystem", icon: "Handshake" },
    ],
  },
  {
    key: "chairman-message",
    name: "ChairmanMessage",
    enabled: true,
    eyebrow: "LEADERSHIP PERSPECTIVE",
    title: "CHAIRMAN'S MESSAGE",
    subtitle: "Pioneering India's Organic & Sustainable Transformation",
    description: "Welcome to Bharat Organic Expo 2027. Our mission is to accelerate the growth of certified organic farming, empower sustainable entrepreneurs, and connect Indian producers with international trade networks.",
    secondaryDescription: "Together with our esteemed Advisory Board, we invite industry leaders, farmers, and innovators to join this transformative journey towards a healthier planet.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    imageAlt: "Chairman - Bharat Organic Expo",
    logoImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    quote: "Empowering grassroots organic agriculture with global market access.",
    buttonLabel: "READ FULL MESSAGE",
    buttonHref: "/about",
  },
  {
    key: "advisory-grid",
    name: "AdvisoryBoardGrid",
    enabled: true,
    eyebrow: "MEET OUR BOARD",
    title: "DISTINGUISHED ADVISORY BOARD MEMBERS",
    subtitle: "Eminent experts driving strategy, innovation, and international partnerships",
    items: [
      { title: "Dr. Arvind Kumar", label: "Organic Agri-Tech Specialist", description: "Former Senior Advisor at ICAR with 25+ years in soil health and bio-fertilizer innovation.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Meera Deshmukh", label: "Sustainable Business Strategist", description: "Pioneer in eco-friendly packaging and green supply chain logistics across South Asia.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Rajiv Singhania", label: "AYUSH & Natural Healthcare Leader", description: "Promoter of holistic wellness summits and herbal product certification standards.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
    ],
  },
  {
    key: "why-join-advisory",
    name: "WhyJoinAdvisory",
    enabled: true,
    eyebrow: "STRATEGIC IMPACT",
    title: "WHY JOIN THE ADVISORY BOARD?",
    subtitle: "Shape policies, mentor innovators, and steer global organic initiatives",
    items: [
      { title: "Policy Advocacy & Standards", description: "Influence national certification frameworks and organic trade guidelines.", icon: "ShieldCheck" },
      { title: "Global Network Expansion", description: "Connect directly with international delegations, embassies, and B2B buyers.", icon: "Globe" },
      { title: "Innovation Mentorship", description: "Guide high-potential agritech startups and eco-enterprises.", icon: "TrendingUp" },
    ],
  },
  {
    key: "advisory-partners",
    name: "AdvisoryPartners",
    enabled: true,
    eyebrow: "COLLABORATING ORGANIZATIONS",
    title: "INSTITUTIONAL & INDUSTRY PARTNERS",
    subtitle: "Supported by premier government bodies, trade federations, and organic councils",
    items: [
      { title: "APEDA", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Namo Gange Trust", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Organic India Alliance", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
    ],
  },
  {
    key: "nominate-banner",
    name: "NominateBanner",
    enabled: true,
    eyebrow: "JOIN OUR VISION",
    title: "NOMINATE AN ADVISORY BOARD MEMBER",
    subtitle: "Know a visionary leader in organic farming, AYUSH, or green tech?",
    description: "We invite nominations for industry stalwarts who wish to contribute towards building India's premier organic trade ecosystem.",
    buttonLabel: "SUBMIT NOMINATION",
    buttonHref: "/contact",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
  },
];
