import { LandingSectionContent } from "./landingContent";

export const defaultBlogSections: LandingSectionContent[] = [
  {
    key: "blog-hero",
    name: "BlogHero",
    enabled: true,
    eyebrow: "BHARAT ORGANIC EXPO",
    titlePrimary: "BLOGS &",
    titleSecondary: "NEWS",
    subtitle: "Insights. Innovation. Impact.",
    description: "Stay updated with the latest trends, expert perspectives, innovations and success stories shaping India's organic food, agriculture and sustainable products industry.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    imageAlt: "Bharat Organic Expo Blog Banner",
    secondaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
  },
  {
    key: "blog-stats",
    name: "BlogStats",
    enabled: true,
    title: "EXPO INSIGHT HIGHLIGHTS",
    items: [
      { title: "500+", subtitle: "ARTICLES & CASE STUDIES", icon: "BookOpen" },
      { title: "250K+", subtitle: "MONTHLY READERS", icon: "Users" },
      { title: "50+", subtitle: "EXPERT CONTRIBUTORS", icon: "Award" },
      { title: "100%", subtitle: "VERIFIED ORGANIC KNOWLEDGE", icon: "ShieldCheck" },
    ],
  },
  {
    key: "blog-featured",
    name: "BlogFeatured",
    enabled: true,
    eyebrow: "FEATURED STORY",
    title: "THE FUTURE OF ORGANIC CERTIFICATION IN INDIA",
    subtitle: "How digital traceability & bio-standards are empowering smallholder farmers",
    description: "An in-depth study on government policies, export trends, and consumer demand driving certified organic staples across national markets.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    imageAlt: "Featured Organic Article",
    buttonLabel: "READ FULL ARTICLE",
    buttonHref: "/blog",
  },
  {
    key: "blog-latest",
    name: "BlogLatest",
    enabled: true,
    eyebrow: "RECENT PUBLICATIONS",
    title: "LATEST NEWS & INDUSTRY ARTICLES",
    subtitle: "Discover fresh perspectives on organic farming, agritech, and wellness",
    buttonLabel: "VIEW ALL ARTICLES",
    buttonHref: "/blog",
    items: [
      { title: "Sustainable Packaging Trends 2027", label: "Eco-Tech", description: "How biodegradable packaging is replacing single-use plastics in organic retail.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Soil Health & Regenerative Agriculture", label: "Farming", description: "Best practices for chemical-free soil restoration and organic yield optimization.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "B2B Export Growth for Herbal Products", label: "Trade", description: "Navigating international compliance and global market expansion for AYUSH brands.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
    ],
  },
  {
    key: "blog-experts",
    name: "BlogExperts",
    enabled: true,
    eyebrow: "THOUGHT LEADERSHIP",
    title: "EXPERT COLUMNISTS & RESEARCHERS",
    subtitle: "Insights from leading agronomists, policymakers, and organic innovators",
    items: [
      { title: "Dr. Sunita Rao", label: "Senior Agronomist", description: "Expert in microbial soil inoculants and natural pest management.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Vikram Malhotra", label: "Organic Trade Analyst", description: "Specializes in B2B buyer matchmaking and international export regulations.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
    ],
  },
  {
    key: "blog-videos",
    name: "BlogVideos",
    enabled: true,
    eyebrow: "MULTIMEDIA & INTERVIEWS",
    title: "EXPO VIDEO HIGHLIGHTS & INTERVIEWS",
    subtitle: "Watch keynote addresses, panel discussions, and exhibitor showcases",
    items: [
      { title: "Keynote: Scaling Organic Supply Chains", videoUrl: "https://www.youtube.com", description: "Highlights from Arogya Sangoshthi knowledge conference." },
      { title: "Exhibitor Spotlight: Bio-Pesticide Breakthroughs", videoUrl: "https://www.youtube.com", description: "Live product demo at Pragati Maidan." },
    ],
  },
  {
    key: "blog-reports",
    name: "BlogReports",
    enabled: true,
    eyebrow: "RESEARCH & DOWNLOADS",
    title: "INDUSTRY REPORTS & MARKET STUDIES",
    subtitle: "Download comprehensive whitepapers on organic sector growth and trade forecasts",
    items: [
      { title: "India Organic Food Market Report 2027", href: "/blog", description: "Full market breakdown with export trends and consumer demography." },
      { title: "AYUSH & Natural Healthcare Trends", href: "/blog", description: "Whitepaper on preventive wellness and international demand." },
    ],
  },
  {
    key: "blog-cta",
    name: "BlogCta",
    enabled: true,
    eyebrow: "STAY INFORMED",
    title: "SUBSCRIBE TO BHARAT ORGANIC INSIGHTS",
    subtitle: "Get bi-weekly organic market reports, conference updates, and exhibitor alerts delivered to your inbox.",
    inputPlaceholder: "Enter your corporate email address...",
    buttonLabel: "SUBSCRIBE NOW",
    buttonHref: "/newsletter",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
  },
];
