import { LandingSectionContent } from "./landingContent";

export const defaultBuyerSellerMeetSections: LandingSectionContent[] = [
  {
    key: "buyer-seller-meet-hero",
    name: "HeroSection",
    enabled: true,
    titlePrimary: "BUYER-SELLER",
    titleSecondary: "MEET 2027",
    subtitle: "Connect with the Right Businesses. Create Real Opportunities. A focused B2B networking platform at Bharat Organic Expo 2027.",
    date: "19-21 February 2027",
    location: "Hall 12, Bharat Mandapam, New Delhi",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    logoImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    buttonLabel: "REGISTER AS A BUYER",
    buttonHref: "/registration/buyer-registration",
    secondaryButtonLabel: "PARTICIPATE AS AN EXHIBITOR",
    secondaryButtonHref: "/registration/book-a-stand",
  },
  {
    key: "buyer-seller-feature-strip",
    name: "FeatureStrip",
    enabled: true,
    title: "B2B MEET HIGHLIGHTS",
    items: [
      { title: "Curated Meetings", subtitle: "Relevant Connections", icon: "Users" },
      { title: "Verified Business", subtitle: "Profiles", icon: "CheckCircle" },
      { title: "Industry Focused", subtitle: "Networking", icon: "Target" },
      { title: "New Opportunities", subtitle: "& Partnerships", icon: "ArrowUpRight" },
      { title: "Business Growth", subtitle: "& Expansion", icon: "TrendingUp" },
    ],
  },
  {
    key: "buyer-seller-about",
    name: "AboutSection",
    enabled: true,
    eyebrow: "ABOUT THE B2B MEET",
    title: "Bridging Sourcing Requirements with Trusted Producers",
    description: "The Buyer–Seller Meet at Bharat Organic Expo 2027 is a dedicated B2B networking platform designed to connect verified organic producers, manufacturers, and exporters with serious domestic & international buyers.",
    lowerTitle: "Streamlined Matchmaking for Maximum ROI",
    lowerDescription: "Pre-scheduled 1-on-1 meetings, dedicated B2B lounges, and personalized matchmaking ensure every interaction creates real commercial value.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    items: [
      { title: "Direct Sourcing", description: "Source directly from certified organic farmers, FPOs & manufacturers without intermediaries.", icon: "Handshake" },
      { title: "Pre-Scheduled B2B Meetings", description: "Maximize efficiency with targeted, pre-matched business meetings aligned with your sourcing needs.", icon: "CalendarDays" },
      { title: "Global & Domestic Buyers", description: "Connect with importers, retail chains, e-commerce brands & institutional procurers.", icon: "Globe" },
      { title: "Verified Exhibitors & Products", description: "Explore certified organic, herbal & sustainable products backed by quality standards.", icon: "ShieldCheck" },
    ],
  },
  {
    key: "who-can-participate",
    name: "WhoCanParticipate",
    enabled: true,
    eyebrow: "PARTICIPANT PROFILE",
    title: "Who Can Participate?",
    subtitle: "Connecting Sourcing Leaders with Certified Producers",
    items: [
      { title: "Supermarkets & Retail Chains", description: "Sourcing organic staples, personal care & packaged goods.", icon: "Store" },
      { title: "Importers & Exporters", description: "Expanding international organic trade networks.", icon: "Globe" },
      { title: "E-Commerce Platforms", description: "Curating premium organic and sustainable brands.", icon: "ShoppingCart" },
      { title: "Institutional Buyers & HORECA", description: "Bulk sourcing for hospitality & wellness centers.", icon: "Building2" },
      { title: "Organic Producers & FPOs", description: "Showcasing certified organic produce to direct buyers.", icon: "Sprout" },
      { title: "Manufacturers & Brand Owners", description: "Exploring OEM, contract manufacturing & private label deals.", icon: "Factory" },
    ],
  },
  {
    key: "what-to-source",
    name: "WhatToSource",
    enabled: true,
    eyebrow: "PRODUCT CATEGORIES",
    title: "What Can You Source?",
    subtitle: "Explore a Comprehensive Range of Certified Organic & Natural Products",
    items: [
      { title: "Organic Food & Beverages", description: "Certified pulses, grains, superfoods, teas, oils & packaged goods.", icon: "Apple" },
      { title: "AYUSH, Herbal & Wellness", description: "Ayurvedic medicines, herbal extracts, essential oils & supplements.", icon: "Leaf" },
      { title: "Organic Agriculture & Bio-Inputs", description: "Bio-fertilizers, organic seeds, soil enhancers & eco farming tools.", icon: "Sprout" },
      { title: "Natural Personal Care", description: "Herbal skincare, organic cosmetics & eco-friendly hygiene products.", icon: "Droplet" },
      { title: "GreenTech & Packaging", description: "Biodegradable packaging & sustainable AgriTech solutions.", icon: "Box" },
      { title: "Trade & Certification Services", description: "Testing labs, export agencies & organic certification bodies.", icon: "FileCheck" },
    ],
  },
  {
    key: "why-join-meet",
    name: "WhyJoin",
    enabled: true,
    eyebrow: "BENEFITS OF PARTICIPATING",
    title: "Why Join the Buyer–Seller Meet?",
    items: [
      { title: "Pre-Matched Networking", description: "Save time with curated B2B schedules pre-aligned to your specific sourcing demands." },
      { title: "Verified Business Credentials", description: "Engage with vetted buyers and suppliers backed by valid certifications." },
      { title: "High Conversion Potential", description: "Meet decision-makers ready to negotiate, partner, and place direct orders." },
      { title: "Exclusive B2B Lounge Access", description: "Conduct private business meetings in dedicated, comfortable networking zones." },
    ],
  },
  {
    key: "how-it-works-meet",
    name: "HowItWorks",
    enabled: true,
    eyebrow: "SIMPLE B2B PROCESS",
    title: "How It Works",
    subtitle: "4 Steps to Successful Business Networking",
    items: [
      { num: "01", title: "Register Your Interest", description: "Fill in your sourcing or supply requirements on our portal." },
      { num: "02", title: "Profile Screening & Matching", description: "Our team verifies credentials and matches relevant buyers & sellers." },
      { num: "03", title: "Receive Meeting Schedule", description: "Get your personalized B2B meeting schedule prior to the event." },
      { num: "04", title: "Meet & Close Deals", description: "Connect 1-on-1 at Bharat Mandapam and expand your business." },
    ],
  },
  {
    key: "connect-with-section",
    name: "ConnectWith",
    enabled: true,
    title: "Connect with Industry Leaders",
    subtitle: "Build Partnerships That Drive Growth",
    description: "Join over 1,000+ domestic and international buyers sourcing authentic organic products.",
    buttonLabel: "REGISTER NOW",
    buttonHref: "/registration/buyer-registration",
  },
  {
    key: "buyer-seller-cta",
    name: "CtaBanner",
    enabled: true,
    title: "Ready to Expand Your Business Network?",
    description: "Reserve your slot for the Buyer–Seller Meet at Bharat Organic Expo 2027 today.",
    buttonLabel: "REGISTER AS A BUYER",
    buttonHref: "/registration/buyer-registration",
    secondaryButtonLabel: "EXHIBIT WITH US",
    secondaryButtonHref: "/registration/book-a-stand",
  },
];
