import { LandingSectionContent } from "./landingContent";

export const defaultBuyerSellerMeetSections: LandingSectionContent[] = [
  {
    key: "buyer-seller-meet-hero",
    name: "HeroSection",
    enabled: true,
    eyebrow: "BUYER-SELLER MEET 2027",
    titlePrimary: "BUYER-SELLER",
    titleSecondary: "MEET 2027",
    subtitle: "Connect with the Right Businesses. Create Real Opportunities. A focused B2B networking platform at Bharat Organic Expo 2027.",
    date: "19-21 February 2027",
    location: "Hall 12, Bharat Mandapam, New Delhi",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    logoImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    buttonLabel: "REGISTER AS A BUYER",
    buttonHref: "/registration/buyer-registration",
    secondaryButtonLabel: "PARTICIPATE AS AN EXHIBITOR",
    secondaryButtonHref: "/registration/book-a-stand",
  },
  {
    key: "buyer-seller-feature-strip",
    name: "FeatureStrip",
    enabled: true,
    title: "B2B MEET HIGHLIGHTS",
    items: [
      { title: "Curated Meetings", subtitle: "Relevant Connections", icon: "Users" },
      { title: "Verified Business", subtitle: "Profiles", icon: "CheckCircle" },
      { title: "Industry Focused", subtitle: "Networking", icon: "Target" },
      { title: "New Opportunities", subtitle: "& Partnerships", icon: "ArrowUpRight" },
      { title: "Business Growth", subtitle: "& Expansion", icon: "TrendingUp" },
    ],
  },
  {
    key: "buyer-seller-about",
    name: "AboutSection",
    enabled: true,
    eyebrow: "ABOUT BUYER-SELLER MEET",
    title: "ABOUT BUYER-SELLER MEET",
    description: "The Buyer-Seller Meet at Bharat Organic Expo 2027 is designed to facilitate focused B2B interactions between participating exhibitors and relevant business buyers.",
    lowerTitle: "The platform enables participants to explore:",
    items: [
      { title: "Sourcing & Distribution" },
      { title: "Institutional Supply" },
      { title: "Procurement & Private Label" },
      { title: "Strategic Partnerships" },
      { title: "Export-Import Opportunities" },
      { title: "Business Collaborations" },
    ],
  },
  {
    key: "who-can-participate",
    name: "WhoCanParticipate",
    enabled: true,
    eyebrow: "WHO CAN PARTICIPATE AS A BUYER?",
    title: "WHO CAN PARTICIPATE AS A BUYER?",
    subtitle: "Meet Suppliers Across the Complete Organic Industry Ecosystem",
    sideTitle: "MEET.\nCONNECT.\nCOLLABORATE.\nGROW.",
    sideDescription: "Be part of India's leading B2B networking platform for the organic industry.",
    items: [
      { title: "Importers & Exporters", description: "Explore products, sourcing opportunities and global partnerships." },
      { title: "Distributors & Wholesalers", description: "Discover new brands and expand product portfolios." },
      { title: "Retail Chains & Supermarkets", description: "Source organic, natural, wellness and sustainable products." },
      { title: "E-commerce & Marketplace Buyers", description: "Discover emerging and established consumer brands." },
      { title: "Institutional Buyers", description: "Connect with manufacturers and suppliers for institutional procurement requirements." },
      { title: "Hotels, Restaurants & HoReCa", description: "Source food, beverages, wellness and sustainable products." },
      { title: "Manufacturers & Private Label Buyers", description: "Explore contract manufacturing, ingredients, private-label opportunities." },
      { title: "Corporate Procurement Teams", description: "Identify relevant products, suppliers and sustainable sourcing solutions." },
      { title: "International Trade Delegations", description: "Explore Indian suppliers, manufacturers and potential trade partnerships." },
    ],
  },
  {
    key: "what-to-source",
    name: "WhatToSource",
    enabled: true,
    eyebrow: "WHAT CAN BUYERS SOURCE?",
    title: "WHAT CAN BUYERS SOURCE?",
    subtitle: "6 Industry Segments. One Business Platform.",
    items: [
      { title: "ORGANIC FOOD & NUTRITION", description: "Food • Beverages • Nutraceuticals • Functional Nutrition" },
      { title: "AYUSH, HERBAL & WELLNESS", description: "Ayurveda • Herbal • Wellness • Traditional Health Solutions" },
      { title: "ORGANIC AGRICULTURE", description: "Farming • Inputs • Seeds • Bio-Inputs" },
      { title: "NATURAL LIVING & PERSONAL CARE", description: "Beauty • Personal Care • Natural Lifestyle Products" },
      { title: "GREENTECH & SUSTAINABILITY", description: "AgriTech • GreenTech • Sustainable Packaging • Processing" },
      { title: "TRADE, CERTIFICATION & GLOBAL BUSINESS", description: "Certification • Export • Import • Trade & Business Services" },
    ],
  },
  {
    key: "why-join-meet",
    name: "WhyJoin",
    enabled: true,
    eyebrow: "WHY JOIN THE BUYER-SELLER MEET?",
    title: "WHY JOIN THE BUYER-SELLER MEET?",
    subTitle: "For Buyers",
    secondaryTitle: "For Exhibitors",
    items: [
      { title: "Discover New Suppliers", category: "buyer" },
      { title: "Compare Products & Solutions", category: "buyer" },
      { title: "Explore New Brands", category: "buyer" },
      { title: "Develop Sourcing Partnerships", category: "buyer" },
      { title: "Build Industry Connections", category: "buyer" },
      { title: "Meet Relevant Buyers", category: "exhibitor" },
      { title: "Generate B2B Opportunities", category: "exhibitor" },
      { title: "Expand Market Reach", category: "exhibitor" },
      { title: "Explore Strategic Partnerships", category: "exhibitor" },
      { title: "Build Brand Awareness", category: "exhibitor" },
    ],
  },
  {
    key: "how-it-works-meet",
    name: "HowItWorks",
    enabled: true,
    eyebrow: "HOW IT WORKS",
    title: "HOW IT WORKS",
    items: [
      { num: "01", title: "REGISTER", description: "Submit your business profile and areas of interest." },
      { num: "02", title: "PROFILE REVIEW", description: "Registration details are reviewed for relevance to the Buyer-Seller Meet." },
      { num: "03", title: "BUSINESS MATCHING", description: "Relevant buyer and seller interests are identified based on available profiles." },
      { num: "04", title: "MEETING SCHEDULING", description: "Eligible participants receive meeting information/schedules, subject to availability." },
      { num: "05", title: "MEET AT THE EXPO", description: "Participate in focused B2B interactions during Bharat Organic Expo 2027." },
    ],
  },
  {
    key: "connect-with-section",
    name: "ConnectWith",
    enabled: true,
    title: "WHO WILL YOU CONNECT WITH?",
    items: [
      { title: "Brands" },
      { title: "Manufacturers" },
      { title: "Producers" },
      { title: "Suppliers" },
      { title: "Importers" },
      { title: "Exporters" },
      { title: "Distributors" },
      { title: "Wholesalers" },
      { title: "Retailers" },
      { title: "E-commerce Buyers" },
      { title: "HoReCa Buyers" },
      { title: "Trade Bodies" },
      { title: "International Delegations" },
    ],
  },
  {
    key: "buyer-seller-cta",
    name: "CtaBanner",
    enabled: true,
    title: "READY TO CONNECT WITH NEW BUSINESS OPPORTUNITIES?",
    description: "Join the Buyer-Seller Meet at Bharat Organic Expo 2027.",
    buttonLabel: "REGISTER AS A BUYER",
    buttonHref: "/registration/buyer-registration",
    secondaryButtonLabel: "PARTICIPATE AS AN EXHIBITOR",
    secondaryButtonHref: "/registration/book-a-stand",
    contactEmail: "info@namogangewellness.com",
    phoneNumber: "+91 96549 00525",
  },
];
