import { LandingSectionContent } from "./landingContent";

export const defaultExhibitionCategoriesSections: LandingSectionContent[] = [
  {
    key: "exhibition-hero",
    name: "Exhibition Categories Hero",
    enabled: true,
    eyebrow: "EXHIBITION SECTORS",
    titlePrimary: "EXPLORE OUR",
    titleSecondary: "EXHIBITION CATEGORIES",
    subtitle: "Showcasing the entire organic & natural ecosystem.",
    description: "Discover innovative products, sustainable solutions, certified organic produce, and cutting-edge technologies across key sector categories.",
    date: "19–21 February 2027",
    location: "Hall 12, Bharat Mandapam, New Delhi",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    buttonLabel: "BOOK YOUR STALL",
    buttonHref: "/registration/book-a-stand",
    secondaryButtonLabel: "REGISTER AS VISITOR",
    secondaryButtonHref: "/registration/visitor-registration",
  },
  {
    key: "exhibition-sectors",
    name: "Sector Showcase Overview",
    enabled: true,
    title: "EXHIBITION SECTOR HIGHLIGHTS",
    description: "Key product segments represented at Bharat Organic Expo 2027.",
    items: [
      { title: "Organic Agriculture & Farming Inputs", icon: "Sprout", description: "Bio-fertilizers, organic seeds, pest management, soil health solutions" },
      { title: "Organic Food & Beverages", icon: "Leaf", description: "Certified organic staples, health drinks, processed foods, snacks" },
      { title: "Ayush, Herbal & Wellness", icon: "HeartPulse", description: "Ayurvedic products, herbal supplements, wellness remedies" },
      { title: "Natural Beauty & Personal Care", icon: "Sparkles", description: "Organic cosmetics, clean skincare, herbal hygiene products" },
      { title: "AgriTech & Smart Farming", icon: "Zap", description: "Smart irrigation, farm automation, vertical farming tech" },
      { title: "Sustainable Packaging & Eco-Products", icon: "ShieldCheck", description: "Biodegradable packaging, compostable materials, eco-friendly goods" },
      { title: "Dairy, Livestock & Bio-Energy", icon: "Building2", description: "Organic dairy, sustainable livestock care, biogas & bio-energy" },
      { title: "Nutraceuticals & Superfoods", icon: "Award", description: "Dietary supplements, functional foods, natural proteins" },
      { title: "Certification, Testing & Trade Services", icon: "FileText", description: "Organic certification agencies, testing labs, trade promotion" },
    ],
  },
  {
    key: "exhibition-cta",
    name: "Exhibition Call to Action",
    enabled: true,
    title: "READY TO SHOWCASE YOUR PRODUCTS TO THOUSANDS OF BUYERS?",
    description: "Reserve your stall space today at Bharat Organic Expo 2027.",
    buttonLabel: "BOOK YOUR STALL NOW",
    buttonHref: "/registration/book-a-stand",
  },
  {
    key: "category-showcase-food-beverages",
    name: "Showcase: Organic Food & Beverages",
    enabled: true,
    eyebrow: "FEATURED CATEGORY SHOWCASE",
    titlePrimary: "ORGANIC FOOD",
    titleSecondary: "& BEVERAGES",
    description: "Discover certified organic grains, pulses, spices, beverages, and packaged organic food from top national & international producers.",
    keyPoint1: "100% Certified Organic Staples & Spices",
    keyPoint2: "Cold-Pressed Oils & Natural Sweeteners",
    keyPoint3: "Ready-to-Eat Organic Snacks & Superfoods",
    keyPoint4: "Direct Farm-to-Fork Sourcing Connections",
    buttonLabel: "EXHIBIT IN THIS CATEGORY",
    buttonHref: "/registration/book-a-stand",
  },
  {
    key: "category-showcase-ayush",
    name: "Showcase: Ayush, Ayurveda & Herbal",
    enabled: true,
    eyebrow: "FEATURED CATEGORY SHOWCASE",
    titlePrimary: "AYUSH, AYURVEDA",
    titleSecondary: "& HERBAL WELLNESS",
    description: "Explore ancient wellness remedies, authentic Ayurvedic formulations, herbal extracts, and holistic health products.",
    keyPoint1: "GMP Certified Ayurvedic Medicines & Formulations",
    keyPoint2: "Pure Herbal Extracts & Essential Oils",
    keyPoint3: "Wellness & Preventive Healthcare Solutions",
    keyPoint4: "B2B Export Opportunities for Global Buyers",
    buttonLabel: "EXHIBIT IN AYUSH SECTOR",
    buttonHref: "/registration/book-a-stand",
  },
  {
    key: "category-showcase-farming",
    name: "Showcase: Organic & Natural Farming",
    enabled: true,
    eyebrow: "FEATURED CATEGORY SHOWCASE",
    titlePrimary: "ORGANIC & NATURAL",
    titleSecondary: "FARMING PRODUCE",
    description: "Showcasing sustainable farming techniques, organic horticulture, medicinal plants, and eco-friendly agricultural produce.",
    keyPoint1: "Certified Organic Fruits, Vegetables & Herbs",
    keyPoint2: "Farmer Producer Organizations (FPOs) & Cooperatives",
    keyPoint3: "Sustainable Soil & Biodiversity Management",
    keyPoint4: "Contract Farming & Bulk Sourcing Programs",
    buttonLabel: "JOIN AS FARMING EXHIBITOR",
    buttonHref: "/registration/book-a-stand",
  },
  {
    key: "category-showcase-inputs",
    name: "Showcase: Bio-Inputs & Soil Health",
    enabled: true,
    eyebrow: "FEATURED CATEGORY SHOWCASE",
    titlePrimary: "BIO-FERTILIZERS",
    titleSecondary: "& ORGANIC INPUTS",
    description: "High-quality bio-inputs, bio-pesticides, organic compost, vermicompost, and soil conditioning solutions for sustainable yield.",
    keyPoint1: "NPOP Approved Bio-Fertilizers & Bio-Pesticides",
    keyPoint2: "Microbial Inoculants & Mycorrhiza Tech",
    keyPoint3: "Soil Moisture & Health Management Tools",
    keyPoint4: "Organic Seed Varieties & Seed Treatment",
    buttonLabel: "EXHIBIT BIO-INPUTS",
    buttonHref: "/registration/book-a-stand",
  },
  {
    key: "category-showcase-dairy",
    name: "Showcase: Dairy, Livestock & Bio-Energy",
    enabled: true,
    eyebrow: "FEATURED CATEGORY SHOWCASE",
    titlePrimary: "ORGANIC DAIRY",
    titleSecondary: "& BIO-ENERGY SOLUTIONS",
    description: "Organic A2 dairy products, sustainable livestock management, bio-gas digesters, and renewable bio-energy solutions.",
    keyPoint1: "A2 Organic Milk, Ghee, Butter & Artisanal Cheese",
    keyPoint2: "Ethical & Chemical-Free Cattle Breeding",
    keyPoint3: "Biogas Plants & Waste-to-Energy Tech",
    keyPoint4: "Animal Nutrition & Herbal Veterinary Care",
    buttonLabel: "BOOK DAIRY STALL",
    buttonHref: "/registration/book-a-stand",
  },
  {
    key: "category-showcase-beauty",
    name: "Showcase: Natural Beauty & Clean Care",
    enabled: true,
    eyebrow: "FEATURED CATEGORY SHOWCASE",
    titlePrimary: "NATURAL BEAUTY",
    titleSecondary: "& CLEAN PERSONAL CARE",
    description: "Chemical-free skincare, organic cosmetics, herbal hair care, and eco-certified personal hygiene products.",
    keyPoint1: "Toxin-Free, Paraben-Free Organic Skincare",
    keyPoint2: "Cruelty-Free & Vegan Cosmetic Formulations",
    keyPoint3: "Aromatherapy & Herbal Body Care",
    keyPoint4: "Private Labeling & OEM Manufacturing",
    buttonLabel: "EXHIBIT BEAUTY BRAND",
    buttonHref: "/registration/book-a-stand",
  },
  {
    key: "category-showcase-nutraceuticals",
    name: "Showcase: Nutraceuticals & Superfoods",
    enabled: true,
    eyebrow: "FEATURED CATEGORY SHOWCASE",
    titlePrimary: "NUTRACEUTICALS",
    titleSecondary: "& FUNCTIONAL SUPERFOODS",
    description: "Plant-based proteins, dietary supplements, immunity boosters, and bio-active natural ingredients.",
    keyPoint1: "Organic Superfoods & Functional Powders",
    keyPoint2: "Plant-Based Protein Supplements",
    keyPoint3: "Vitamin & Herbal Immunity Boosters",
    keyPoint4: "Clinical & FSSAI Compliant Formulations",
    buttonLabel: "EXHIBIT NUTRACEUTICALS",
    buttonHref: "/registration/book-a-stand",
  },
  {
    key: "category-showcase-packaging",
    name: "Showcase: Sustainable Packaging & Processing",
    enabled: true,
    eyebrow: "FEATURED CATEGORY SHOWCASE",
    titlePrimary: "SUSTAINABLE PACKAGING",
    titleSecondary: "& ECO-PROCESSING TECH",
    description: "Biodegradable packaging materials, compostable pouches, cold-chain solutions, and eco-processing machinery.",
    keyPoint1: "Compostable & Biodegradable Packaging Films",
    keyPoint2: "Plastic-Free Paper & Sugarcane Bagasse Pouches",
    keyPoint3: "Solar-Powered Grain Milling & Processing Tech",
    keyPoint4: "Cold Chain Storage & Post-Harvest Protection",
    buttonLabel: "EXHIBIT PACKAGING TECH",
    buttonHref: "/registration/book-a-stand",
  },
  {
    key: "category-showcase-agritech",
    name: "Showcase: AgriTech & Green Innovation",
    enabled: true,
    eyebrow: "FEATURED CATEGORY SHOWCASE",
    titlePrimary: "AGRITECH & GREEN",
    titleSecondary: "INNOVATION HUB",
    description: "IoT soil sensors, drone spraying, precision agriculture software, AI-driven crop analytics, and green tech.",
    keyPoint1: "AI & IoT Precision Agriculture Sensors",
    keyPoint2: "Agricultural Drones for Bio-Spraying",
    keyPoint3: "Solar Pumping & Drip Irrigation Systems",
    keyPoint4: "Carbon Credit & Traceability Software Platforms",
    buttonLabel: "EXHIBIT AGRITECH SOLUTION",
    buttonHref: "/registration/book-a-stand",
  },
  {
    key: "category-showcase-certification",
    name: "Showcase: Certification, Testing & Trade",
    enabled: true,
    eyebrow: "FEATURED CATEGORY SHOWCASE",
    titlePrimary: "CERTIFICATION",
    titleSecondary: "& EXPORT TRADE SERVICES",
    description: "NPOP/NOP accreditation bodies, residue testing laboratories, export promotion councils, and organic trade logistics.",
    keyPoint1: "NPOP, USDA Organic, EU & JAS Certification Bodies",
    keyPoint2: "NABL Accredited Pesticide & Residue Testing Labs",
    keyPoint3: "APEDA & Trade Promotion Helpdesks",
    keyPoint4: "Global Export Logistics & Compliance Advisory",
    buttonLabel: "EXHIBIT TRADE SERVICES",
    buttonHref: "/registration/book-a-stand",
  },
];
