import { LandingSectionContent } from "./landingContent";

export const fallbackExhibitors = [
    { _id: "ex1", title: "THE WORLD OF MARĪCT", location: "India", category: "ORGANIC FOOD", order: 1, websiteUrl: "" },
    { _id: "ex2", title: "SNOWFLAKZ", location: "India", category: "ORGANIC FOOD", order: 2, websiteUrl: "" },
    { _id: "ex3", title: "The Pahari Life", location: "Himachal Pradesh", category: "ORGANIC FOOD", order: 3, websiteUrl: "" },
    { _id: "ex4", title: "Heritiage Oils", location: "India", category: "ORGANIC FOOD", order: 4, websiteUrl: "" },
    { _id: "ex5", title: "Tripti Natural Himachal", location: "Himachal Pradesh", category: "NATURAL CARE", order: 5, websiteUrl: "" },
    { _id: "ex6", title: "FARMIYA ORGANICS", location: "India", category: "AGRICULTURE", order: 6, websiteUrl: "" },
    { _id: "ex7", title: "Saatwik Aaruyeda", location: "India", category: "AYURVEDA", order: 7, websiteUrl: "" },
    { _id: "ex8", title: "The Himavan Essence", location: "India", category: "AYURVEDA", order: 8, websiteUrl: "" },
    { _id: "ex9", title: "Prabhushree", location: "India", category: "ORGANIC FOOD", order: 9, websiteUrl: "" },
    { _id: "ex10", title: "SPICES & HERBS", location: "India", category: "ORGANIC FOOD", order: 10, websiteUrl: "" },
    { _id: "ex11", title: "Etbar", location: "India", category: "NATURAL CARE", order: 11, websiteUrl: "" },
    { _id: "ex12", title: "Safe Agri", location: "India", category: "AGRICULTURE", order: 12, websiteUrl: "" },
    { _id: "ex13", title: "SHREE HARI", location: "India", category: "AYURVEDA", order: 13, websiteUrl: "" },
    { _id: "ex14", title: "Ropuiliani", location: "India", category: "ORGANIC FOOD", order: 14, websiteUrl: "" },
    { _id: "ex15", title: "VEER FITNESS", location: "India", category: "HEALTH & WELLNESS", order: 15, websiteUrl: "" },
    { _id: "ex16", title: "Pratham Pahal", location: "India", category: "AGRICULTURE", order: 16, websiteUrl: "" },
    { _id: "ex17", title: "V S Natural", location: "India", category: "NATURAL CARE", order: 17, websiteUrl: "" },
    { _id: "ex18", title: "Viraj Agro Foods", location: "India", category: "ORGANIC FOOD", order: 18, websiteUrl: "" },
    { _id: "ex19", title: "CFEI", location: "India", category: "AGRICULTURE", order: 19, websiteUrl: "" },
    { _id: "ex20", title: "PELLE NUDA", location: "India", category: "NATURAL CARE", order: 20, websiteUrl: "" },
    { _id: "ex21", title: "Dadu Fresh", location: "India", category: "ORGANIC FOOD", order: 21, websiteUrl: "" },
    { _id: "ex22", title: "Bhukranti", location: "India", category: "AGRICULTURE", order: 22, websiteUrl: "" },
    { _id: "ex23", title: "Nutrelis", location: "India", category: "HEALTH & WELLNESS", order: 23, websiteUrl: "" },
    { _id: "ex24", title: "Herbal Eco", location: "India", category: "AYURVEDA", order: 24, websiteUrl: "" },
    { _id: "ex25", title: "Khasiyat", location: "India", category: "ORGANIC FOOD", order: 25, websiteUrl: "" },
    { _id: "ex26", title: "Shree Ratnam", location: "India", category: "AYURVEDA", order: 26, websiteUrl: "" },
    { _id: "ex27", title: "Star Holo India", location: "India", category: "OTHERS", order: 27, websiteUrl: "" },
    { _id: "ex28", title: "Baiso Organics", location: "India", category: "ORGANIC FOOD", order: 28, websiteUrl: "" },
    { _id: "ex29", title: "Kaki maa", location: "India", category: "ORGANIC FOOD", order: 29, websiteUrl: "" },
    { _id: "ex30", title: "Moorahav Organic", location: "India", category: "AGRICULTURE", order: 30, websiteUrl: "" },
    { _id: "ex31", title: "Mohan Ghee", location: "India", category: "ORGANIC FOOD", order: 31, websiteUrl: "" },
    { _id: "ex32", title: "Shabari Naturals", location: "India", category: "NATURAL CARE", order: 32, websiteUrl: "" },
    { _id: "ex33", title: "Raheja Solar Food Processing pvt. ltd", location: "India", category: "AGRICULTURE", order: 33, websiteUrl: "" },
    { _id: "ex34", title: "Shanara", location: "India", category: "NATURAL CARE", order: 34, websiteUrl: "" },
    { _id: "ex35", title: "Good And Grow", location: "India", category: "AGRICULTURE", order: 35, websiteUrl: "" },
    { _id: "ex36", title: "E-Bio-Cares", location: "India", category: "AYURVEDA", order: 36, websiteUrl: "" },
    { _id: "ex37", title: "Panchtattav foods Pvt Ltd", location: "India", category: "ORGANIC FOOD", order: 37, websiteUrl: "" },
    { _id: "ex38", title: "Sharekhan", location: "India", category: "OTHERS", order: 38, websiteUrl: "" },
    { _id: "ex39", title: "Bhartiye Crafts", location: "India", category: "OTHERS", order: 39, websiteUrl: "" },
    { _id: "ex40", title: "Vinayak Group", location: "India", category: "AGRICULTURE", order: 40, websiteUrl: "" },
    { _id: "ex41", title: "Sri Yamuna Essence", location: "India", category: "AYURVEDA", order: 41, websiteUrl: "" },
    { _id: "ex42", title: "Kajah Balm & Oil", location: "India", category: "AYURVEDA", order: 42, websiteUrl: "" },
    { _id: "ex43", title: "Soultatva", location: "India", category: "ORGANIC FOOD", order: 43, websiteUrl: "" },
    { _id: "ex44", title: "Shroonius", location: "India", category: "ORGANIC FOOD", order: 44, websiteUrl: "" },
    { _id: "ex45", title: "Skyrr Up", location: "India", category: "HEALTH & WELLNESS", order: 45, websiteUrl: "" },
    { _id: "ex46", title: "Achyutam Aahar", location: "India", category: "ORGANIC FOOD", order: 46, websiteUrl: "" },
    { _id: "ex47", title: "Grunwald", location: "India", category: "OTHERS", order: 47, websiteUrl: "" },
    { _id: "ex48", title: "Viridian", location: "India", category: "AYURVEDA", order: 48, websiteUrl: "" },
];

export const HERO_STATS = [
    { value: "200+", label: "Exhibiting Brands" },
    { value: "8,000+", label: "Trade Visitors" },
    { value: "50+", label: "Expert Speakers" },
    { value: "2 Days", label: "Of Networking & Business" },
];

export const BOTTOM_STATS = [
    { value: "200+", label: "Exhibitors" },
    { value: "8,000+", label: "Visitors" },
    { value: "3 Days", label: "Of Knowledge" },
    { value: "PAN India", label: "Participation" },
    { value: "B2B + B2C", label: "Business Opportunity" },
];

export const defaultExhibitorsSections: LandingSectionContent[] = [
  {
    key: "exhibitors-hero",
    name: "HeroSection",
    enabled: true,
    title: "Meet Leading Exhibitors at Bharat Organic Expo",
    subtitle: "Explore 200+ Verified Organic, Ayurveda, AgriTech & Sustainable Brands",
    description: "Browse our exhibitors across Organic Food, AYUSH, Natural Care, AgriTech, Bio-Inputs, and Sustainable Solutions.",
    items: HERO_STATS.map((s) => ({ value: s.value, label: s.label })),
  },
  {
    key: "exhibitors-list",
    name: "ExhibitorsListSection",
    enabled: true,
    title: "Exhibitors Directory",
    subtitle: "Browse All Participating Brands",
    items: fallbackExhibitors.map((ex) => ({
      _id: ex._id,
      title: ex.title,
      location: ex.location,
      category: ex.category,
      order: ex.order,
      websiteUrl: ex.websiteUrl || "",
    })),
  },
  {
    key: "exhibitors-bottom-stats",
    name: "BottomStatsSection",
    enabled: true,
    title: "EXPO HIGHLIGHTS",
    items: BOTTOM_STATS.map((s) => ({ value: s.value, label: s.label })),
  },
];
