import { LandingSectionContent } from "./landingContent";

export const defaultGallerySections: LandingSectionContent[] = [
  {
    key: "gallery-hero",
    name: "HeroSection",
    enabled: true,
    title: "GLIMPSES",
    subtitle: "Moments of Knowledge, Collaboration & Wellness",
    description: "Relive the inspiring moments from past editions of Organic Expo where experts, researchers and industry leaders came together to shape the future of organic trade and sustainable living.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
  },
  {
    key: "gallery-years-filter",
    name: "YearsFilter",
    enabled: true,
    title: "Filter by Year",
    items: [
      { title: "All Years" },
      { title: "2026 Edition" },
      { title: "2025 Edition" },
      { title: "2024 Edition" },
      { title: "2023 Edition" },
    ],
  },
  {
    key: "gallery-category-filter",
    name: "CategoryFilter",
    enabled: true,
    title: "Filter by Activity Category",
    items: [
      { title: "All Activities" },
      { title: "Inauguration" },
      { title: "Exhibition (Expo)" },
      { title: "Scientific Sessions" },
      { title: "Networking" },
      { title: "Panel Discussions" },
      { title: "Awards" },
      { title: "Workshops" },
      { title: "Speakers" },
      { title: "Cultural Programs" },
    ],
  },
  {
    key: "gallery-grid",
    name: "GalleryGrid",
    enabled: true,
    title: "Photo Gallery Showcase",
    items: [
      { title: "Grand Inaugural Ceremony", category: "Inauguration", year: "2025", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Expo Pavilion & Stalls", category: "Exhibition (Expo)", year: "2025", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Scientific & Research Sessions", category: "Scientific Sessions", year: "2025", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Delegates & Buyer Interaction", category: "Networking", year: "2025", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Sustainable Future Panel", category: "Panel Discussions", year: "2025", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Exhibition Product Display", category: "Exhibition (Expo)", year: "2025", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Organic Excellence Awards", category: "Awards", year: "2025", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Cultural Dance & Heritage", category: "Cultural Programs", year: "2025", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Industry Leaders Networking", category: "Networking", year: "2024", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Distinguished Keynote Address", category: "Speakers", year: "2025", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Honor & Certificate Felicitation", category: "Awards", year: "2024", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Organic Farming Masterclass", category: "Workshops", year: "2025", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
    ],
  },
  {
    key: "gallery-counters",
    name: "Counters",
    enabled: true,
    title: "EXPO IMPACT IN NUMBERS",
    items: [
      { val: "50,000+", label: "HAPPY VISITORS", icon: "Users" },
      { val: "500+", label: "EXHIBITORS", icon: "Building2" },
      { val: "25+", label: "COUNTRIES PARTICIPATED", icon: "Globe" },
      { val: "100+", label: "EXPERT SPEAKERS", icon: "Mic" },
    ],
  },
  {
    key: "gallery-video-highlights",
    name: "VideoHighlights",
    enabled: true,
    title: "VIDEO HIGHLIGHTS",
    subtitle: "Watch Keynotes, Panel Discussions & Expo Memories",
    items: [
      { title: "Inauguration Highlights", videoUrl: "https://www.instagram.com/reel/DV-xaNXCBGl/", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Scientific Sessions", videoUrl: "https://www.instagram.com/reel/DVqfgxYkyua/", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Expo Highlights 2025", videoUrl: "https://www.instagram.com/reel/DWJH1yIiOkZ/", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Cultural Programs", videoUrl: "https://www.instagram.com/reel/DWI04E2CEPN/", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Panel Discussions", videoUrl: "https://www.instagram.com/reel/DXQvmcbESsn/", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Workshops & Demos", videoUrl: "https://www.instagram.com/reel/DXLmSBljEmT/", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Awards & Recognition", videoUrl: "https://www.instagram.com/reel/DXJC2lhkum9/", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Organic Innovations", videoUrl: "https://www.instagram.com/reel/DW-l2FkjW7q/", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
    ],
  },
  {
    key: "gallery-join-banner",
    name: "JoinUsBanner",
    enabled: true,
    title: "Be Part of Bharat Organic Expo 2027",
    description: "Join India's premier organic trade show to showcase your products, connect with global buyers, and grow your brand.",
    buttonLabel: "BOOK YOUR STALL NOW",
    buttonHref: "/registration/book-a-stand",
    secondaryButtonLabel: "REGISTER AS VISITOR",
    secondaryButtonHref: "/registration/visitor-registration",
  },
];
