import { LandingSectionContent } from "./landingContent";

export const defaultMsmeSections: LandingSectionContent[] = [
  {
    key: "msme-pms-banner",
    name: "MsmePmsBanner",
    enabled: true,
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    logoImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    secondaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    eyebrow: "MSME procurement & marketing support",
    titlePrimary: "MSME PMS Scheme",
    titleSecondary: "Exhibition Support",
    subtitle: "Exhibit. Connect. Grow with Government Support",
    description: "Eligible Micro & Small Enterprises can explore financial assistance for participation in Bharat Organic Expo 2027 under the applicable Procurement & Marketing Support (PMS) Scheme.",
    date: "19-21 February 2027",
    location: "Hall 12, Bharat Mandapam, New Delhi",
    buttonLabel: "CHECK PMS ELIGIBILITY",
    buttonHref: "/participate/msme/eligibility-check",
    secondaryButtonLabel: "GET PMS SUPPORT",
    secondaryButtonHref: "tel:+9654900525",
  },
  {
    key: "feature-strip",
    name: "FeatureStrip",
    enabled: true,
    title: "MSME SCHEME HIGHLIGHTS",
    items: [
      { title: "Curated Meetings", subtitle: "Relevant Connections", icon: "Users" },
      { title: "Verified Business", subtitle: "Profiles", icon: "CheckCircle" },
      { title: "Industry Focused", subtitle: "Networking", icon: "Target" },
      { title: "New Opportunities", subtitle: "& Partnerships", icon: "ArrowUpRight" },
      { title: "Business Growth", subtitle: "& Expansion", icon: "TrendingUp" },
    ],
  },
  {
    key: "official-recognition",
    name: "OfficialRecognitionBanner",
    enabled: true,
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    logoImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    secondaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    tertiaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    quaternaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    title: "Official Government Recognition & Approvals",
    items: [
      { title: "Government Approved Scheme", icon: "Award", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Transparent Process", icon: "CheckCircle", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Timely Support", icon: "Clock", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Hassle-free Documentation", icon: "FileText", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "For Micro & Small Enterprises Only", icon: "Users", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
    ],
  },
  {
    key: "msme-pms-scheme",
    name: "MsmePmsScheme",
    enabled: true,
    eyebrow: "KNOW THE SCHEME",
    title: "What is the MSME PMS Scheme?",
    description: "The Procurement & Marketing Support (PMS) Scheme is an initiative of the Ministry of MSME aimed at improving market access for Micro & Small Enterprises. Eligible MSMEs can explore applicable financial assistance for participation in approved trade fairs and exhibitions.",
    lowerTitle: "The PMS Scheme empowers MSMEs to participate, promote and prosper.",
    lowerDescription: "More Participation. More Exposure. More Growth.",
    items: [
      {
        title: "Market Access",
        description: "Explore new domestic and international markets for your products and services.",
        icon: "Globe",
      },
      {
        title: "Exhibition Support",
        description: "Reduce the cost of participation in approved exhibitions and trade fairs.",
        icon: "Store",
      },
      {
        title: "Buyer Connections",
        description: "Meet buyers, distributors and industry professionals to grow your business network.",
        icon: "Users",
      },
      {
        title: "Business Growth",
        description: "Strengthen your brand, increase visibility and create new business opportunities.",
        icon: "TrendingUp",
      },
    ],
  },
  {
    key: "msme-assistance-breakdown",
    name: "Pmsfinancialassistancebanner",
    enabled: true,
    title: "Financial Assistance Breakdown & Percentages",
    subtitle: "Category-wise Stall Subsidies Under PMS Scheme",
    description: "Financial assistance provided under the scheme varies based on enterprise category and owner profile.",
    items: [
      { title: "General Category MSMEs", value: "Up to 80%", description: "Eligible space rent support as per scheme rules." },
      { title: "SC/ST / Women / Divyang Enterprises", value: "Up to 100%", description: "Full eligible space rent assistance subject to ceilings." },
      { title: "NER / Special Category Regions", value: "Up to 100%", description: "Maximum admissible assistance under PMS." },
      { title: "Contingency Support Ceiling", value: "Up to ₹25,000*", description: "Covers travel, freight, and publicity within total budget." },
    ],
  },
  {
    key: "msme-support-cover",
    name: "PmsSupportCoverSection",
    enabled: true,
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    logoImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    secondaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    eyebrow: "What Can Your PMS Support Cover?",
    title: "More Than Just Stall Space Rent",
    subtitle: "Up to ₹1.50 LAKH per Eligible Enterprise / Event",
    description: "For eligible MSME participation in an approved exhibition, PMS assistance may cover eligible exhibition space rent along with specified contingency expenses, subject to applicable scheme guidelines and approval.",
    quote: "100% of eligible contingency expenditure, subject to the applicable ceiling and PMS guidelines.",
    legalNotice: "Important: The ₹25,000 contingency support is part of the overall assistance ceiling and not ₹25,000 over and above ₹1.50 lakh.",
    items: [
      { num: "1", title: "SPACE RENT", subtitle: "Stall / Built-up Space", description: "Up to 80% / 100%* of eligible space rent", icon: "Store", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { num: "2", title: "TRAVEL", subtitle: "One Representative*", description: "Eligible travel expenditure*", icon: "Plane", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { num: "3", title: "FREIGHT", subtitle: "Exhibition Material", description: "Transportation of products / display material*", icon: "Truck", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { num: "4", title: "PUBLICITY", subtitle: "Eligible Promotion", description: "Eligible publicity expenditure*", icon: "Megaphone", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Additional Contingency Support", value: "Up to ₹25,000*", features: ["Travel", "Freight", "Publicity"], image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
    ],
  },
  {
    key: "pms-support-section",
    name: "Pmssupportsection",
    enabled: true,
    title: "How We Assist You With Your PMS Application",
    subtitle: "End-to-End Assistance for Seamless Approval",
    items: [
      { title: "Eligibility Assessment", description: "Quick evaluation of your Udyam Registration & category suitability.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Documentation Guidance", description: "Complete checklist and preparation of required PMS submission docs.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Application Submission", description: "Filing and tracking your application on the official MSME portal.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Exhibition Space Booking", description: "Allotment of stall space at Bharat Organic Expo 2027 upon approval.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
    ],
  },
  {
    key: "whats-next-banner",
    name: "Whatsnextbanner",
    enabled: true,
    title: "What's Next? Simple Steps To Apply",
    items: [
      { num: "1", title: "Check Eligibility", description: "Verify Udyam category and PMS guidelines.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { num: "2", title: "Submit Documents", description: "Upload Udyam, Aadhaar, PAN & company details.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { num: "3", title: "Get Assistance", description: "Receive official verification & stall booking confirmation.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
    ],
  },
  {
    key: "need-help-section",
    name: "NeedHelpSection",
    enabled: true,
    title: "Need Assistance With MSME PMS Application?",
    description: "Our dedicated MSME support team is here to guide you through eligibility, documents, and portal registration.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    buttonLabel: "TALK TO MSME ADVISOR",
    buttonHref: "tel:+9654900525",
  },
  {
    key: "msme-director-message",
    name: "Msmedirectormessage",
    enabled: true,
    eyebrow: "Hear From MSME Leadership",
    title: "Official Message From MSME Director",
    subtitle: "A message of support and encouragement for all MSMEs participating in Bharat Organic Expo 2027 under the PMS Scheme.",
    quote: "Government of India is committed to empowering MSMEs and creating more opportunities for their growth. We appreciate initiatives like Bharat Organic Expo 2027 that provide a strong platform for MSMEs to showcase their products, build business, and expand globally.",
    authorName: "Shri. S. C. L. Das",
    authorDesignation: "Development Commissioner (MSME), Ministry of Micro, Small & Medium Enterprises, Government of India",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    logoImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    secondaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
  },
  {
    key: "msme-documents",
    name: "Pmsdocumentsbanner",
    enabled: true,
    title: "Required Documents for PMS Application",
    subtitle: "Checklist for Hassle-Free Filing",
    items: [
      { title: "Udyam Registration Certificate", description: "Valid Udyam Certificate (MSME Registration).", icon: "FileText", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "PAN & GST Certificate", description: "PAN Card and GST Registration Certificate.", icon: "CreditCard", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Bank Details", description: "Cancelled Cheque / Bank Passbook First Page.", icon: "Building2", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Exhibition Participation Proof", description: "Stall Allocation / Participation Confirmation / Contract.", icon: "Award", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Invoices & Payment Proof", description: "Tax Invoices and Payment Receipts / Proofs.", icon: "Receipt", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Participation Evidence", description: "Photos, Videos, Press Coverage, Brochures, etc.", icon: "Image", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Dispatch / Delivery Challan", description: "Delivery Challans / Despatch Documents.", icon: "Truck", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "E-Way Bill (If Applicable)", description: "E-Way Bills for dispatch of goods.", icon: "FileCheck", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Declaration Form", description: "Self-declaration / Undertaking as per PMS format.", icon: "FileEdit", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "MSME Affidavit / Undertaking", description: "Affidavit / Undertaking on non-duplication of claim.", icon: "ShieldCheck", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Cancelled Cheque / Bank Proof", description: "Bank account proof in the name of the enterprise.", icon: "CheckCircle", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Any Other Document (If Required)", description: "Additional documents as per PMS guidelines.", icon: "Folder", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
    ],
  },
  {
    key: "why-participate-section",
    name: "Whyparticipatesection",
    enabled: true,
    title: "Why Participate Under MSME PMS Scheme?",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    items: [
      { title: "Maximum Cost Savings", description: "Significantly reduce your overall exhibition budget with government subsidies.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Pan-India Exposure", description: "Connect with buyers, distributors & trade delegates at national scale.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
      { title: "Government Recognition", description: "Gain enhanced credibility and official trust among B2B buyers.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg" },
    ],
  },
  {
    key: "msme-faq",
    name: "FaqBanner",
    enabled: true,
    title: "FAQ",
    subtitle: "Frequently Asked Questions",
    eyebrow: "Supporting MSMEs Growth Together",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    secondaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    logoImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    items: [
      {
        question: "Is Bharat Organic Expo approved under PMS?",
        answer: "Yes, subject to the exact approval/sanction received for Bharat Organic Expo 2027. Official approval details should be displayed above.",
        icon: "BadgeCheck",
        image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
      },
      {
        question: "Who can apply for PMS support?",
        answer: "Eligible Micro & Small Enterprises meeting applicable Udyam Registration, business activity, event and PMS requirements may apply.",
        icon: "Users",
        image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
      },
      {
        question: "Is reimbursement guaranteed?",
        answer: "No. Event approval does not automatically guarantee reimbursement. Individual eligibility, documentation and final approval are required.",
        icon: "FileQuestion",
        image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
      },
      {
        question: "I am not Udyam registered. Can your team help?",
        answer: "Yes. Our team can guide you regarding the Udyam Registration process and subsequent preliminary PMS eligibility screening.",
        icon: "IdCard",
        image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
      },
      {
        question: "Will your team support the claim process?",
        answer: "Yes. Our PMS Support Team can provide applicable process and documentation guidance for claim filing. Final approval and reimbursement remain with the competent MSME authority.",
        icon: "Headset",
        image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
      },
    ],
  },
  {
    key: "pms-final-cta",
    name: "PmsFinalCtaSection",
    enabled: true,
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    secondaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    tertiaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    headingBefore: "Ready to Explore",
    headingHighlight: "PMS Support?",
    subtitle: "Start with a Simple Eligibility Check.",
    leftCardTitle: "Already Udyam registered?",
    leftCardDescription: "Upload your certificate and let us conduct a preliminary screening.",
    rightCardTitle: "Not registered yet?",
    rightCardDescription: "Start with Udyam Registration guidance.",
    primaryButton: "CHECK YOUR PMS ELIGIBILITY",
    secondaryButton: "GET UDYAM REGISTRATION GUIDANCE",
    supportText: "Talk to PMS Support Team",
    services: [
      "Registration Guidance",
      "Eligibility Screening",
      "Application Support",
      "Documentation",
      "Claim Assistance",
    ],
    disclaimerTitle: "IMPORTANT DISCLAIMER",
    disclaimerText: "Bharat Organic Expo / Organiser provides PMS facilitation, preliminary eligibility screening, Udyam Registration guidance, documentation and claim-process assistance. Event approval does not constitute automatic approval of an individual MSME application or reimbursement claim. Eligibility, sanction, permissible assistance and reimbursement are subject to applicable Ministry of MSME guidelines and decisions of the competent authority.",
    buttonLabel: "CHECK PMS ELIGIBILITY",
    buttonHref: "/participate/msme/eligibility-check",
    secondaryButtonLabel: "CALL MSME HELPLINE",
    secondaryButtonHref: "tel:+9654900525",
  },
];

