import { LandingSectionContent } from "./landingContent";

export const defaultMsmeSections: LandingSectionContent[] = [
  {
    key: "msme-pms-banner",
    name: "MsmePmsBanner",
    enabled: true,
    eyebrow: "MSME procurement & marketing support",
    titlePrimary: "MSME PMS Scheme",
    titleSecondary: "Exhibition Support",
    subtitle: "Exhibit. Connect. Grow with Government Support",
    description: "Eligible Micro & Small Enterprises can explore financial assistance for participation in Bharat Organic Expo 2027 under the applicable Procurement & Marketing Support (PMS) Scheme.",
    date: "19-21 February 2027",
    location: "Hall 12, Bharat Mandapam, New Delhi",
    buttonLabel: "CHECK PMS ELIGIBILITY",
    buttonHref: "/participate/msme/eligibility-check",
    secondaryButtonLabel: "GET PMS SUPPORT",
    secondaryButtonHref: "tel:+9654900525",
  },
  {
    key: "msme-pms-scheme",
    name: "MsmePmsScheme",
    enabled: true,
    eyebrow: "KNOW THE SCHEME",
    title: "What is the MSME PMS Scheme?",
    description: "The Procurement & Marketing Support (PMS) Scheme is an initiative of the Ministry of MSME aimed at improving market access for Micro & Small Enterprises. Eligible MSMEs can explore applicable financial assistance for participation in approved trade fairs and exhibitions.",
    lowerTitle: "The PMS Scheme empowers MSMEs to participate, promote and prosper.",
    lowerDescription: "More Participation. More Exposure. More Growth.",
    items: [
      { title: "Market Access", description: "Explore new domestic and international markets for your products and services." },
      { title: "Exhibition Support", description: "Reduce the cost of participation in approved exhibitions and trade fairs." },
      { title: "Buyer Connections", description: "Meet buyers, distributors and industry professionals to grow your business network." },
      { title: "Business Growth", description: "Strengthen your brand, increase visibility and create new business opportunities." },
    ],
  },
  {
    key: "msme-support-cover",
    name: "PmsSupportCoverSection",
    enabled: true,
    eyebrow: "What Can Your PMS Support Cover?",
    title: "More Than Just Stall Space Rent",
    subtitle: "Up to ₹1.50 LAKH per Eligible Enterprise / Event",
    description: "For eligible MSME participation in an approved exhibition, PMS assistance may cover eligible exhibition space rent along with specified contingency expenses, subject to applicable scheme guidelines and approval.",
    quote: "100% of eligible contingency expenditure, subject to the applicable ceiling and PMS guidelines.",
    legalNotice: "Important: The ₹25,000 contingency support is part of the overall assistance ceiling and not ₹25,000 over and above ₹1.50 lakh.",
    items: [
      { num: "1", title: "SPACE RENT", subtitle: "Stall / Built-up Space", description: "Up to 80% / 100%* of eligible space rent" },
      { num: "2", title: "TRAVEL", subtitle: "One Representative*", description: "Eligible travel expenditure*" },
      { num: "3", title: "FREIGHT", subtitle: "Exhibition Material", description: "Transportation of products / display material*" },
      { num: "4", title: "PUBLICITY", subtitle: "Eligible Promotion", description: "Eligible publicity expenditure*" },
      { title: "Additional Contingency Support", value: "Up to ₹25,000*", features: ["Travel", "Freight", "Publicity"] },
    ],
  },
  {
    key: "msme-director-message",
    name: "Msmedirectormessage",
    enabled: true,
    eyebrow: "Hear From MSME Leadership",
    title: "Official Message From MSME Director",
    subtitle: "A message of support and encouragement for all MSMEs participating in Bharat Organic Expo 2027 under the PMS Scheme.",
    quote: "Government of India is committed to empowering MSMEs and creating more opportunities for their growth. We appreciate initiatives like Bharat Organic Expo 2027 that provide a strong platform for MSMEs to showcase their products, build business, and expand globally.",
    authorName: "Shri. S. C. L. Das",
    authorDesignation: "Development Commissioner (MSME), Ministry of Micro, Small & Medium Enterprises, Government of India",
  },
  {
    key: "msme-official-recognition",
    name: "OfficialRecognitionBanner",
    enabled: true,
    title: "Official Government Recognition & Approvals",
    items: [
      { title: "Government Approved Scheme" },
      { title: "Transparent Process" },
      { title: "Timely Support" },
      { title: "Hassle-free Documentation" },
      { title: "For Micro & Small Enterprises Only" },
    ],
  },
  {
    key: "msme-documents",
    name: "Pmsdocumentsbanner",
    enabled: true,
    title: "Required Documents for PMS Application",
  },
  {
    key: "msme-assistance",
    name: "Pmsfinancialassistancebanner",
    enabled: true,
    title: "Financial Assistance Breakdown & Percentages",
  },
  {
    key: "msme-faq",
    name: "FaqBanner",
    enabled: true,
    title: "Frequently Asked Questions (FAQ)",
  },
];
