import { LandingSectionContent } from "./landingContent";

export const defaultMsmeSections: LandingSectionContent[] = [
  {
    key: "msme-pms-banner",
    name: "MsmePmsBanner",
    enabled: true,
    image: "",
    logoImage: "",
    secondaryImage: "",
    eyebrow: "MSME procurement & marketing support",
    titlePrimary: "MSME PMS Scheme",
    titleSecondary: "Exhibition Support",
    subtitle: "Exhibit. Connect. Grow with Government Support",
    description: "Eligible Micro & Small Enterprises can explore financial assistance for participation in Bharat Organic Expo 2027 under the applicable Procurement & Marketing Support (PMS) Scheme.",
    date: "19-21 February 2027",
    location: "Hall 12, Bharat Mandapam, New Delhi",
    buttonLabel: "CHECK PMS ELIGIBILITY",
    buttonHref: "/participate/msme/eligibility-check",
    secondaryButtonLabel: "GET PMS SUPPORT",
    secondaryButtonHref: "tel:+9654900525",
  },
  {
    key: "feature-strip",
    name: "FeatureStrip",
    enabled: true,
    title: "MSME SCHEME HIGHLIGHTS",
    items: [
      { title: "Curated Meetings", subtitle: "Relevant Connections", icon: "Users" },
      { title: "Verified Business", subtitle: "Profiles", icon: "CheckCircle" },
      { title: "Industry Focused", subtitle: "Networking", icon: "Target" },
      { title: "New Opportunities", subtitle: "& Partnerships", icon: "ArrowUpRight" },
      { title: "Business Growth", subtitle: "& Expansion", icon: "TrendingUp" },
    ],
  },
  {
    key: "official-recognition",
    name: "OfficialRecognitionBanner",
    enabled: true,
    image: "",
    logoImage: "",
    secondaryImage: "",
    tertiaryImage: "",
    quaternaryImage: "",
    title: "Official Government Recognition & Approvals",
    items: [
      { title: "Government Approved Scheme", icon: "Award", image: "" },
      { title: "Transparent Process", icon: "CheckCircle", image: "" },
      { title: "Timely Support", icon: "Clock", image: "" },
      { title: "Hassle-free Documentation", icon: "FileText", image: "" },
      { title: "For Micro & Small Enterprises Only", icon: "Users", image: "" },
    ],
  },
  {
    key: "msme-pms-scheme",
    name: "MsmePmsScheme",
    enabled: true,
    eyebrow: "KNOW THE SCHEME",
    title: "What is the MSME PMS Scheme?",
    description: "The Procurement & Marketing Support (PMS) Scheme is an initiative of the Ministry of MSME aimed at improving market access for Micro & Small Enterprises. Eligible MSMEs can explore applicable financial assistance for participation in approved trade fairs and exhibitions.",
    lowerTitle: "The PMS Scheme empowers MSMEs to participate, promote and prosper.",
    lowerDescription: "More Participation. More Exposure. More Growth.",
    items: [
      {
        title: "Market Access",
        description: "Explore new domestic and international markets for your products and services.",
        icon: "Globe",
      },
      {
        title: "Exhibition Support",
        description: "Reduce the cost of participation in approved exhibitions and trade fairs.",
        icon: "Store",
      },
      {
        title: "Buyer Connections",
        description: "Meet buyers, distributors and industry professionals to grow your business network.",
        icon: "Users",
      },
      {
        title: "Business Growth",
        description: "Strengthen your brand, increase visibility and create new business opportunities.",
        icon: "TrendingUp",
      },
    ],
  },
  {
    key: "msme-assistance-breakdown",
    name: "Pmsfinancialassistancebanner",
    enabled: true,
    title: "Financial Assistance Breakdown & Percentages",
    subtitle: "Category-wise Stall Subsidies Under PMS Scheme",
    description: "Financial assistance provided under the scheme varies based on enterprise category and owner profile.",
    items: [
      { title: "General Category MSMEs", value: "Up to 80%", description: "Eligible space rent support as per scheme rules." },
      { title: "SC/ST / Women / Divyang Enterprises", value: "Up to 100%", description: "Full eligible space rent assistance subject to ceilings." },
      { title: "NER / Special Category Regions", value: "Up to 100%", description: "Maximum admissible assistance under PMS." },
      { title: "Contingency Support Ceiling", value: "Up to ₹25,000*", description: "Covers travel, freight, and publicity within total budget." },
    ],
  },
  {
    key: "msme-support-cover",
    name: "PmsSupportCoverSection",
    enabled: true,
    image: "",
    logoImage: "",
    secondaryImage: "",
    eyebrow: "What Can Your PMS Support Cover?",
    title: "More Than Just Stall Space Rent",
    subtitle: "Up to ₹1.50 LAKH per Eligible Enterprise / Event",
    description: "For eligible MSME participation in an approved exhibition, PMS assistance may cover eligible exhibition space rent along with specified contingency expenses, subject to applicable scheme guidelines and approval.",
    quote: "100% of eligible contingency expenditure, subject to the applicable ceiling and PMS guidelines.",
    legalNotice: "Important: The ₹25,000 contingency support is part of the overall assistance ceiling and not ₹25,000 over and above ₹1.50 lakh.",
    items: [
      { num: "1", title: "SPACE RENT", subtitle: "Stall / Built-up Space", description: "Up to 80% / 100%* of eligible space rent", icon: "Store", image: "" },
      { num: "2", title: "TRAVEL", subtitle: "One Representative*", description: "Eligible travel expenditure*", icon: "Plane", image: "" },
      { num: "3", title: "FREIGHT", subtitle: "Exhibition Material", description: "Transportation of products / display material*", icon: "Truck", image: "" },
      { num: "4", title: "PUBLICITY", subtitle: "Eligible Promotion", description: "Eligible publicity expenditure*", icon: "Megaphone", image: "" },
      { title: "Additional Contingency Support", value: "Up to ₹25,000*", features: ["Travel", "Freight", "Publicity"], image: "" },
    ],
  },
  {
    key: "pms-support-section",
    name: "Pmssupportsection",
    enabled: true,
    title: "How We Assist You With Your PMS Application",
    subtitle: "End-to-End Assistance for Seamless Approval",
    items: [
      { title: "Eligibility Assessment", description: "Quick evaluation of your Udyam Registration & category suitability.", image: "" },
      { title: "Documentation Guidance", description: "Complete checklist and preparation of required PMS submission docs.", image: "" },
      { title: "Application Submission", description: "Filing and tracking your application on the official MSME portal.", image: "" },
      { title: "Exhibition Space Booking", description: "Allotment of stall space at Bharat Organic Expo 2027 upon approval.", image: "" },
    ],
  },
  {
    key: "whats-next-banner",
    name: "Whatsnextbanner",
    enabled: true,
    title: "What's Next? Simple Steps To Apply",
    items: [
      { num: "1", title: "Check Eligibility", description: "Verify Udyam category and PMS guidelines.", image: "" },
      { num: "2", title: "Submit Documents", description: "Upload Udyam, Aadhaar, PAN & company details.", image: "" },
      { num: "3", title: "Get Assistance", description: "Receive official verification & stall booking confirmation.", image: "" },
    ],
  },
  {
    key: "need-help-section",
    name: "NeedHelpSection",
    enabled: true,
    title: "Need Assistance With MSME PMS Application?",
    description: "Our dedicated MSME support team is here to guide you through eligibility, documents, and portal registration.",
    image: "",
    buttonLabel: "TALK TO MSME ADVISOR",
    buttonHref: "tel:+9654900525",
  },
  {
    key: "msme-director-message",
    name: "Msmedirectormessage",
    enabled: true,
    eyebrow: "Hear From MSME Leadership",
    title: "Official Message From MSME Director",
    subtitle: "A message of support and encouragement for all MSMEs participating in Bharat Organic Expo 2027 under the PMS Scheme.",
    quote: "Government of India is committed to empowering MSMEs and creating more opportunities for their growth. We appreciate initiatives like Bharat Organic Expo 2027 that provide a strong platform for MSMEs to showcase their products, build business, and expand globally.",
    authorName: "Shri. S. C. L. Das",
    authorDesignation: "Development Commissioner (MSME), Ministry of Micro, Small & Medium Enterprises, Government of India",
    image: "",
    logoImage: "",
    secondaryImage: "",
  },
  {
    key: "msme-documents",
    name: "Pmsdocumentsbanner",
    enabled: true,
    title: "Required Documents for PMS Application",
    subtitle: "Checklist for Hassle-Free Filing",
    items: [
      { title: "Udyam Registration Certificate", description: "Valid Udyam Certificate (MSME Registration).", icon: "FileText", image: "" },
      { title: "PAN & GST Certificate", description: "PAN Card and GST Registration Certificate.", icon: "CreditCard", image: "" },
      { title: "Bank Details", description: "Cancelled Cheque / Bank Passbook First Page.", icon: "Building2", image: "" },
      { title: "Exhibition Participation Proof", description: "Stall Allocation / Participation Confirmation / Contract.", icon: "Award", image: "" },
      { title: "Invoices & Payment Proof", description: "Tax Invoices and Payment Receipts / Proofs.", icon: "Receipt", image: "" },
      { title: "Participation Evidence", description: "Photos, Videos, Press Coverage, Brochures, etc.", icon: "Image", image: "" },
      { title: "Dispatch / Delivery Challan", description: "Delivery Challans / Despatch Documents.", icon: "Truck", image: "" },
      { title: "E-Way Bill (If Applicable)", description: "E-Way Bills for dispatch of goods.", icon: "FileCheck", image: "" },
      { title: "Declaration Form", description: "Self-declaration / Undertaking as per PMS format.", icon: "FileEdit", image: "" },
      { title: "MSME Affidavit / Undertaking", description: "Affidavit / Undertaking on non-duplication of claim.", icon: "ShieldCheck", image: "" },
      { title: "Cancelled Cheque / Bank Proof", description: "Bank account proof in the name of the enterprise.", icon: "CheckCircle", image: "" },
      { title: "Any Other Document (If Required)", description: "Additional documents as per PMS guidelines.", icon: "Folder", image: "" },
    ],
  },
  {
    key: "why-participate-section",
    name: "Whyparticipatesection",
    enabled: true,
    title: "Why Participate Under MSME PMS Scheme?",
    image: "",
    items: [
      { title: "Maximum Cost Savings", description: "Significantly reduce your overall exhibition budget with government subsidies.", image: "" },
      { title: "Pan-India Exposure", description: "Connect with buyers, distributors & trade delegates at national scale.", image: "" },
      { title: "Government Recognition", description: "Gain enhanced credibility and official trust among B2B buyers.", image: "" },
    ],
  },
  {
    key: "msme-faq",
    name: "FaqBanner",
    enabled: true,
    title: "FAQ",
    subtitle: "Frequently Asked Questions",
    eyebrow: "Supporting MSMEs Growth Together",
    image: "",
    secondaryImage: "",
    logoImage: "",
    items: [
      {
        question: "Is Bharat Organic Expo approved under PMS?",
        answer: "Yes, subject to the exact approval/sanction received for Bharat Organic Expo 2027. Official approval details should be displayed above.",
        icon: "BadgeCheck",
        image: "",
      },
      {
        question: "Who can apply for PMS support?",
        answer: "Eligible Micro & Small Enterprises meeting applicable Udyam Registration, business activity, event and PMS requirements may apply.",
        icon: "Users",
        image: "",
      },
      {
        question: "Is reimbursement guaranteed?",
        answer: "No. Event approval does not automatically guarantee reimbursement. Individual eligibility, documentation and final approval are required.",
        icon: "FileQuestion",
        image: "",
      },
      {
        question: "I am not Udyam registered. Can your team help?",
        answer: "Yes. Our team can guide you regarding the Udyam Registration process and subsequent preliminary PMS eligibility screening.",
        icon: "IdCard",
        image: "",
      },
      {
        question: "Will your team support the claim process?",
        answer: "Yes. Our PMS Support Team can provide applicable process and documentation guidance for claim filing. Final approval and reimbursement remain with the competent MSME authority.",
        icon: "Headset",
        image: "",
      },
    ],
  },
  {
    key: "pms-final-cta",
    name: "PmsFinalCtaSection",
    enabled: true,
    image: "",
    secondaryImage: "",
    tertiaryImage: "",
    headingBefore: "Ready to Explore",
    headingHighlight: "PMS Support?",
    subtitle: "Start with a Simple Eligibility Check.",
    leftCardTitle: "Already Udyam registered?",
    leftCardDescription: "Upload your certificate and let us conduct a preliminary screening.",
    rightCardTitle: "Not registered yet?",
    rightCardDescription: "Start with Udyam Registration guidance.",
    primaryButton: "CHECK YOUR PMS ELIGIBILITY",
    secondaryButton: "GET UDYAM REGISTRATION GUIDANCE",
    supportText: "Talk to PMS Support Team",
    services: [
      "Registration Guidance",
      "Eligibility Screening",
      "Application Support",
      "Documentation",
      "Claim Assistance",
    ],
    disclaimerTitle: "IMPORTANT DISCLAIMER",
    disclaimerText: "Bharat Organic Expo / Organiser provides PMS facilitation, preliminary eligibility screening, Udyam Registration guidance, documentation and claim-process assistance. Event approval does not constitute automatic approval of an individual MSME application or reimbursement claim. Eligibility, sanction, permissible assistance and reimbursement are subject to applicable Ministry of MSME guidelines and decisions of the competent authority.",
    buttonLabel: "CHECK PMS ELIGIBILITY",
    buttonHref: "/participate/msme/eligibility-check",
    secondaryButtonLabel: "CALL MSME HELPLINE",
    secondaryButtonHref: "tel:+9654900525",
  },
];

export const defaultMsmeEligibilityCheckSections: LandingSectionContent[] = [
  {
    key: "eligibility-hero",
    name: "Eligibility Calculator Hero",
    enabled: true,
    eyebrow: "PMS Eligibility Check",
    titlePrimary: "Your Gateway to",
    titleSecondary: "PMS Support",
    subtitle: "Bharat Organic Expo 2027",
    description: "Upload your official Udyam certificate (PDF/JPEG) for verification.",
    buttonLabel: "UPLOAD & VERIFY",
    secondaryButtonLabel: "Min. 9 sqm Stall Required",
  },
  {
    key: "eligibility-preliminary-status",
    name: "Preliminary Status Banner",
    enabled: true,
    eyebrow: "PRELIMINARY STATUS",
    title: "ELIGIBLE",
    subtitle: "Your enterprise appears eligible for PMS Support.",
    supportTitle: "POTENTIAL PMS SUPPORT",
    supportValue: "UP TO 100%",
    supportDescription: "Eligible Space Rent Assistance*",
    categoryBadge: "Women MSME Category",
    whyTitle: "Why 100%?",
    whyDescription: "Your Udyam record identifies the entrepreneur as Female. Under the applicable PMS assistance category, Women MSMEs may qualify for 100% assistance on eligible built-up space rent, subject to scheme limits and final approval.",
  },
  {
    key: "eligibility-enterprise-details",
    name: "Enterprise Details Breakdown",
    enabled: true,
    title: "YOUR ENTERPRISE DETAILS",
    enterpriseName: "RAMMANI TRADELINK PRIVATE LIMITED",
    enterpriseType: "Micro",
    majorActivity: "Manufacturing",
    organisationType: "Private Limited Company",
    entrepreneurCategory: "General",
    gender: "Female",
    udyamRegDate: "25 May 2026",
    location: "East Delhi, Delhi",
    gstinAvailable: "Yes",
    noteText: "The Udyam certificate confirms Micro classification and Manufacturing as the major activity. The detailed record identifies the entrepreneur as female.",
    matchQuality: "Strong Match",
  },
  {
    key: "eligibility-industry-match",
    name: "Industry & NIC Product Match",
    enabled: true,
    title: "INDUSTRY MATCH FOUND",
    subtitle: "Your registered activities match Bharat Organic Expo.",
    items: [
      { code: "10795", title: "Grinding & Processing of Spices", description: "Food Products → Spices → Manufacturing" },
      { code: "21009", title: "Pharmaceutical & Botanical Products", description: "Pharmaceuticals → Medicinal → Botanical Products → Manufacturing" },
    ],
  },
  {
    key: "eligibility-calculation-steps",
    name: "Calculation Steps & Statuses",
    enabled: true,
    title: "HOW YOUR ELIGIBILITY WAS CALCULATED",
    items: [
      { step: "1", title: "Valid Udyam Registration", subtitle: "UDYAM-DL-02-0118490", statusText: "PASSED" },
      { step: "2", title: "Micro / Small Enterprise", subtitle: "Enterprise Classification: MICRO", statusText: "PASSED" },
      { step: "3", title: "Manufacturing / Service Activity", subtitle: "Major Activity: MANUFACTURING", statusText: "PASSED" },
      { step: "4", title: "Approved Expo Industry Match", subtitle: "Food • Spices • Pharmaceutical • Medicinal • Botanical Products", statusText: "PASSED" },
      { step: "5", title: "Special PMS Category Check", subtitle: "Entrepreneur Gender: FEMALE", statusText: "100% CATEGORY IDENTIFIED*" },
    ],
  },
  {
    key: "eligibility-estimate-card",
    name: "Financial Assistance Estimate",
    enabled: true,
    title: "YOUR ESTIMATED PMS BENEFIT",
    subtitle: "Standard General Category (Up to 80%) vs Applicable Category (Up to 100%)",
    value: "Up to 100%",
    description: "Women MSME Category: Therefore, although the social category shown in Udyam is General, the record separately shows the entrepreneur's gender as Female.",
    contingencyTitle: "ESTIMATE YOUR POTENTIAL ASSISTANCE",
    contingencyValue: "Up to 99,000*",
    contingencyDesc: "Stall Area 9 sqm @ ₹11,500/sqm = Basic Space Rent ₹1,03,500. Estimated Eligible Assistance Up to 99,000*",
  },
  {
    key: "eligibility-verification-alerts",
    name: "Additional Verification & Required Documents",
    enabled: true,
    title: "Additional Verification Required",
    description: "Your preliminary eligibility is positive, but we found a few details that may require supporting documents during application/claim processing:",
    secondaryTitle: "Documents to Keep Ready",
    items: [
      { title: "Udyam Registration Certificate", category: "document" },
      { title: "PAN", category: "document" },
      { title: "GST Registration Certificate", category: "document" },
      { title: "Cancelled Cheque / Bank Details", category: "document" },
      { title: "Bharat Organic Expo Booking Confirmation", category: "document" },
      { title: "Stall Invoice", category: "document" },
      { title: "Payment Proof", category: "document" },
      { title: "Product / Business Activity Proof", category: "document" },
      { title: "Women ownership/promoter proof, if requested", category: "document" },
      { title: "Additional documents required under PMS guidelines", category: "document" },
    ],
  },
  {
    key: "eligibility-final-score-footer",
    name: "Final Eligibility Score & Summary",
    enabled: true,
    title: "Your Preliminary Eligibility Score",
    value: "95",
    subtitle: "High Eligibility",
    recommendationTitle: "Recommended Next Step",
    recommendationDesc: "You appear eligible. Proceed with your Bharat Organic Expo participation.",
    buttonLabel: "Apply for PMS Support",
    buttonHref: "/participate/msme/apply",
    secondaryButtonLabel: "Book Your Stall",
    secondaryButtonHref: "/registration/book-a-stand",
    tertiaryButtonLabel: "Download Eligibility Summary",
    tertiaryButtonHref: "/download/eligibility-summary.pdf",
    quaternaryButtonLabel: "Talk to PMS Support Team",
    quaternaryButtonHref: "tel:+9654900525",
    items: [
      { title: "Micro Enterprise", statusText: "PASSED", icon: "Building2" },
      { title: "Manufacturing", statusText: "PASSED", icon: "Factory" },
      { title: "Approved Industry Match", statusText: "PASSED", icon: "FileCheck2" },
      { title: "Valid Udyam", statusText: "PASSED", icon: "FileCheck2" },
      { title: "Women Category", statusText: "PASSED", icon: "Sprout" },
      { title: "Additional Financial Verification", statusText: "REQUIRES VERIFICATION", icon: "AlertCircle" },
    ],
  },
  {
    key: "eligibility-disclaimer-note",
    name: "Calculator Disclaimer & Guidance Note",
    enabled: true,
    title: "Important Disclaimer",
    description: "This is a preliminary eligibility screening based on the Udyam Registration details provided and the approved industry scope of Bharat Organic Expo. 'Up to 100%' refers to potential assistance on eligible space rent under the applicable PMS category and does not mean a guaranteed refund of the complete exhibition invoice. Final eligibility, admissible stall area, financial ceiling, sanction and reimbursement are subject to applicable Ministry of MSME guidelines and approval by the competent authority.",
    buttonLabel: "Apply for PMS Support",
    buttonHref: "/participate/msme/apply",
    secondaryButtonLabel: "Talk to PMS Support Team",
    secondaryButtonHref: "tel:+9654900525",
  },
];

export const defaultMsmeApplySections: LandingSectionContent[] = [
  {
    key: "msme-apply-hero",
    name: "MSME Apply Hero Banner",
    enabled: true,
    eyebrow: "PMS Scheme",
    titlePrimary: "Apply for ",
    titleSecondary: "PMS SUPPORT",
    subtitle: "Take the next step towards getting up to ₹1.5 Lakh assistance under the MSME Promotion & Marketing Assistance (PMS) Scheme.",
    description: "Eligible Micro & Small Enterprises can claim financial assistance for participation in Bharat Organic Expo 2027.",
    items: [
      { title: "For Eligible", subtitle: "MSMEs Only", icon: "Users" },
      { title: "Up to ₹1.5 Lakh", subtitle: "Assistance", icon: "Percent" },
      { title: "80% or 100%", subtitle: "Reimbursement", icon: "ShieldCheck" },
      { title: "Min. 9 sqm", subtitle: "Stall Required", icon: "Store" },
      { title: "Subject to", subtitle: "Govt. Guidelines", icon: "FileText" },
    ],
  },
  {
    key: "msme-apply-stepper",
    name: "Application Stepper Progress Bar",
    enabled: true,
    title: "Step-by-Step Progress",
    items: [
      { num: "1", title: "Enterprise Details", subtitle: "Basic Info & Udyam" },
      { num: "2", title: "Participation Details", subtitle: "Stall Size & Products" },
      { num: "3", title: "Payment", subtitle: "Subsidy Filing" },
    ],
  },
  {
    key: "msme-apply-form-config",
    name: "Enterprise Form Section Headers",
    enabled: true,
    title: "1. Enterprise Details",
    subtitle: "— Please provide your enterprise information as per Udyam Registration.",
    eyebrow: "Registered Office Address",
    description: "Bank Account Details (For fund transfer, if applicable)",
  },
  {
    key: "msme-apply-sidebar",
    name: "PMS Scheme Guidance & Documents Sidebar",
    enabled: true,
    title: "About PMS Scheme",
    description: "The MSME Promotion & Marketing Assistance (PMS) Scheme provides financial assistance to eligible MSMEs for participating in approved exhibitions.",
    buttonLabel: "View Scheme Guidelines",
    buttonHref: "/participate/msme",
    items: [
      { title: "100% Assistance", subtitle: "For Women Enterprises,\nSC/ST category MSMEs" },
      { title: "80% Assistance", subtitle: "For General (Male)\ncategory MSMEs" },
      { title: "Up to ₹1.5 Lakh", subtitle: "Maximum reimbursement\nper eligible enterprise" },
      { title: "Min. 9 sqm Stall", subtitle: "Minimum stall size required\nto be eligible" },
    ],
  },
  {
    key: "msme-apply-footer-help",
    name: "Application Declaration & Help Banner",
    enabled: true,
    title: "Need Help with PMS Application?",
    description: "Our PMS support team is here to help you with documentation, eligibility, and claim process.",
    buttonLabel: "Talk to PMS Support Team",
    buttonHref: "tel:+911140754187",
    eyebrow: "PMS Helpline",
    date: "Mon - Sat | 10:00 AM - 6:00 PM",
    location: "+91 11 4075 4187",
  },
];

export const defaultMsmeParticipationDetailsSections: LandingSectionContent[] = [
  {
    key: "msme-participation-hero",
    name: "Participation Details Hero Banner",
    enabled: true,
    eyebrow: "PMS SCHEME",
    titlePrimary: "PMS SUPPORT ",
    titleSecondary: "APPLICATION",
    subtitle: "Fill in your participation and stall details to complete your PMS Support application.",
    description: "Provide your booth space choice, product focus, and mandatory event documentation.",
  },
  {
    key: "msme-participation-stepper",
    name: "Participation Stepper Progress Bar",
    enabled: true,
    title: "Step 2: Participation Details",
    items: [
      { num: "1", title: "Enterprise Details", subtitle: "Basic Info & Udyam" },
      { num: "2", title: "Participation Details", subtitle: "Stall Size & Products" },
      { num: "3", title: "Payment", subtitle: "Subsidy Filing" },
    ],
  },
  {
    key: "msme-participation-form-config",
    name: "Participation Form Section Headers",
    enabled: true,
    title: "2. Participation Details",
    subtitle: "— Please provide your Bharat Organic Expo participation details.",
    location: "Bharat Mandapam (Pragati Maidan), New Delhi",
    date: "19 - 21 February 2027",
    eyebrow: "Stall Type",
    description: "Contact Person for PMS Communication",
  },
  {
    key: "msme-participation-sidebar",
    name: "Participation Eligibility & Summary Sidebar",
    enabled: true,
    title: "Your PMS Eligibility Summary",
    statusText: "ELIGIBLE",
    value: "UP TO 100%",
    tag: "Women MSME Category",
    description: "Preliminary Status",
    items: [
      { title: "Documents", description: "Upload required documents" },
      { title: "Declaration", description: "Review & submit application" },
      { title: "Verification", description: "Our team will verify your application" },
      { title: "PMS Assistance", description: "We will guide you through the claim process after the event" },
    ],
  },
  {
    key: "msme-participation-footer-help",
    name: "Participation Help & Support Banner",
    enabled: true,
    title: "Need Help with Space Allotment?",
    description: "Speak with our space allotment team for stall dimension customization or subsidy inquiries.",
    buttonLabel: "Talk to Space Allotment Desk",
    buttonHref: "tel:+911140754187",
    eyebrow: "PMS Helpline",
    date: "Mon - Sat | 10:00 AM - 6:00 PM",
    location: "+91 11 4075 4187",
  },
];

export const defaultMsmeApplyPaymentSections: LandingSectionContent[] = [
  {
    key: "msme-payment-hero",
    name: "PMS Payment Hero Banner",
    enabled: true,
    eyebrow: "PMS SCHEME",
    titlePrimary: "PMS SUPPORT ",
    titleSecondary: "APPLICATION",
    subtitle: "Review and complete payment for your PMS Support application.",
    description: "Review your stall booking breakdown and proceed with encrypted online payment.",
  },
  {
    key: "msme-payment-stepper",
    name: "Payment Stepper Progress Bar",
    enabled: true,
    title: "Step 3: Payment",
    items: [
      { num: "1", title: "Enterprise Details", subtitle: "Basic Info & Udyam" },
      { num: "2", title: "Participation Details", subtitle: "Stall Size & Products" },
      { num: "3", title: "Payment", subtitle: "Subsidy Filing" },
    ],
  },
  {
    key: "msme-payment-main-config",
    name: "Payment Main Section Config",
    enabled: true,
    title: "3. PAYMENT DETAILS",
    subtitle: "Review your payment summary and make the secure payment to complete your PMS Support application.",
    description: "Once payment is successful, your application will be submitted for verification.",
    eyebrow: "CHOOSE PAYMENT METHOD",
    buttonLabel: "Proceed to Payment",
  },
  {
    key: "msme-payment-sidebar",
    name: "Payment Eligibility & Next Steps Sidebar",
    enabled: true,
    title: "Your PMS Eligibility Summary",
    statusText: "ELIGIBLE",
    value: "UP TO 100%",
    tag: "Women MSME Category",
    description: "Preliminary Status",
    items: [
      { title: "Payment", description: "Complete your payment" },
      { title: "Submission", description: "Application will be submitted" },
      { title: "Verification", description: "Our team will verify your application" },
      { title: "PMS Assistance", description: "We will guide you through the claim process after the event" },
    ],
  },
  {
    key: "msme-payment-footer-help",
    name: "Payment Support & Help Desk Banner",
    enabled: true,
    title: "Need Help with Payment or Invoice?",
    description: "Speak with our finance & payment support team for instant assistance with online transaction or GST invoice.",
    buttonLabel: "Talk to Payment Support Desk",
    buttonHref: "tel:+911140754187",
    eyebrow: "PMS Helpline",
    date: "Mon - Sat | 10:00 AM - 6:00 PM",
    location: "+91 11 4075 4187",
  },
];

export const defaultExhibitorLoginSections: LandingSectionContent[] = [
  {
    key: "exhibitor-login-hero",
    name: "Exhibitor Login Portal Hero",
    enabled: true,
    eyebrow: "EXHIBITOR PORTAL",
    titlePrimary: "EXHIBITOR LOGIN",
    titleSecondary: "ACCESS YOUR EXHIBITOR DASHBOARD",
    subtitle: "Manage stall bookings, product showcase, and buyer inquiries.",
    description: "Sign in with your registered email or phone to manage your booth space, submit documents, and access attendee leads for Bharat Organic Expo 2027.",
    buttonLabel: "Sign In",
    secondaryButtonLabel: "Book a Stall",
    secondaryButtonHref: "/registration/book-a-stand",
  },
  {
    key: "exhibitor-login-form-config",
    name: "Exhibitor Login Form Configuration",
    enabled: true,
    title: "Exhibitor Portal Sign In",
    subtitle: "Enter your registered credentials below",
    items: [
      { title: "Registered Email / Phone", placeholder: "e.g. exhibitor@company.com" },
      { title: "Password", placeholder: "••••••••" },
      { title: "Remember Me" },
      { title: "Forgot Password Link", href: "/forgot-password" },
    ],
  },
];

export const defaultBuyerLoginSections: LandingSectionContent[] = [
  {
    key: "buyer-login-hero",
    name: "Buyer Login Portal Hero",
    enabled: true,
    eyebrow: "BUYER & DELEGATE PORTAL",
    titlePrimary: "BUYER LOGIN",
    titleSecondary: "CONNECT WITH TOP ORGANIC PRODUCERS",
    subtitle: "Access B2B buyer-seller networking calendar and meetings.",
    description: "Sign in to view verified exhibitor catalogs, schedule 1-on-1 B2B meetings, and track your trade pass for Bharat Organic Expo 2027.",
    buttonLabel: "Sign In",
    secondaryButtonLabel: "Register as Buyer",
    secondaryButtonHref: "/registration/buyer-registration",
  },
  {
    key: "buyer-login-form-config",
    name: "Buyer Login Form Configuration",
    enabled: true,
    title: "Buyer Portal Sign In",
    subtitle: "Enter your registered buyer credentials below",
    items: [
      { title: "Registered Email / Phone", placeholder: "e.g. buyer@company.com" },
      { title: "Password", placeholder: "••••••••" },
      { title: "Remember Me" },
      { title: "Forgot Password Link", href: "/forgot-password" },
    ],
  },
];

export const defaultDelegatesLoginSections: LandingSectionContent[] = [
  {
    key: "delegates-login-hero",
    name: "Delegates Login Portal Hero",
    enabled: true,
    eyebrow: "CONFERENCE & DELEGATE PORTAL",
    titlePrimary: "DELEGATES LOGIN",
    titleSecondary: "ACCESS CONFERENCE SESSIONS & E-CERTIFICATES",
    subtitle: "View agenda, speaker presentations, and delegate badge.",
    description: "Sign in to your conference delegate account to download session resources, network with keynote speakers, and manage your event schedule.",
    buttonLabel: "Sign In",
    secondaryButtonLabel: "Delegate Registration",
    secondaryButtonHref: "/registration/delegate-registration",
  },
  {
    key: "delegates-login-form-config",
    name: "Delegates Login Form Configuration",
    enabled: true,
    title: "Delegate Portal Sign In",
    subtitle: "Enter your registered delegate credentials below",
    items: [
      { title: "Registered Email / Phone", placeholder: "e.g. delegate@org.com" },
      { title: "Password", placeholder: "••••••••" },
      { title: "Remember Me" },
      { title: "Forgot Password Link", href: "/forgot-password" },
    ],
  },
];

export const defaultUserLoginSections: LandingSectionContent[] = [
  {
    key: "user-login-hero",
    name: "User Login Portal Hero",
    enabled: true,
    eyebrow: "MEMBER & VISITOR PORTAL",
    titlePrimary: "USER LOGIN",
    titleSecondary: "BHARAT ORGANIC EXPO MEMBER PORTAL",
    subtitle: "Access visitor pass, saved exhibitors, and event notifications.",
    description: "Sign in to your member account to view your entry pass, bookmark favorite organic brands, and receive live event updates.",
    buttonLabel: "Sign In",
    secondaryButtonLabel: "Register as Visitor",
    secondaryButtonHref: "/registration/visitor-registration",
  },
  {
    key: "user-login-form-config",
    name: "User Login Form Configuration",
    enabled: true,
    title: "User Portal Sign In",
    subtitle: "Enter your registered account credentials below",
    items: [
      { title: "Email / Phone Number", placeholder: "e.g. user@gmail.com" },
      { title: "Password", placeholder: "••••••••" },
      { title: "Remember Me" },
      { title: "Forgot Password Link", href: "/forgot-password" },
    ],
  },
];

