import { LandingSectionContent } from "./landingContent";

export const defaultParticipateAsExhibitorSections: LandingSectionContent[] = [
  {
    key: "participate-hero",
    name: "ParticipateHero",
    enabled: true,
    eyebrow: "BUYER–SELLER MEET 2027",
    titlePrimary: "WHO CAN",
    titleSecondary: "PARTICIPATE",
    subtitle: "Connect. Collaborate. Grow Together.",
    description: "The Buyer–Seller Meet at Bharat Organic Expo 2027 brings together serious buyers and quality suppliers from across the organic, natural and sustainable industry ecosystem to create meaningful business opportunities.",
    date: "19–21 February 2027",
    location: "Hall 12, Bharat Mandapam, New Delhi",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    imageAlt: "Bharat Organic Expo Buyer-Seller Meet 2027",
    buttonLabel: "REGISTER AS A BUYER",
    buttonHref: "/registration/buyer-registration",
    secondaryButtonLabel: "BOOK YOUR STALL",
    secondaryButtonHref: "/registration/book-a-stand",
  },
  {
    key: "participate-feature-strip",
    name: "ParticipateFeatureStrip",
    enabled: true,
    title: "EXPO HIGHLIGHTS",
    items: [
      { title: "Curated Meetings", subtitle: "Relevant Connections", icon: "Users" },
      { title: "Verified Business", subtitle: "Profiles", icon: "ShieldCheck" },
      { title: "Industry Focused", subtitle: "Networking", icon: "Handshake" },
      { title: "New Opportunities", subtitle: "& Partnerships", icon: "Target" },
      { title: "Business Growth", subtitle: "& Expansion", icon: "TrendingUp" },
    ],
  },
  {
    key: "participate-why",
    name: "ParticipateWhyParticipate",
    enabled: true,
    eyebrow: "WHY BUYERS SHOULD PARTICIPATE?",
    title: "WHY BUYERS SHOULD PARTICIPATE?",
    secondaryTitle: "EXHIBITORS: CONNECT WITH RELEVANT BUYERS",
    secondaryDescription: "Exhibitors at Bharat Organic Expo 2027 can use the Buyer–Seller Meet platform to connect with highly relevant business buyers and explore sourcing, distribution, procurement and strategic partnership opportunities.",
    buttonLabel: "PARTICIPATE AS AN EXHIBITOR",
    buttonHref: "/registration/book-a-stand",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    items: [
      { title: "Meet decision-makers from across the industry" },
      { title: "Explore new sourcing and business opportunities" },
      { title: "Compare products, solutions and suppliers" },
      { title: "Build strong, long-term business relationships" },
      { title: "Expand your market reach and business network" },
      { title: "Find reliable suppliers and quality products" },
    ],
  },
  {
    key: "participate-stats",
    name: "ParticipateStats",
    enabled: true,
    title: "EXPO STATS",
    items: [
      { value: "200+", label: "EXHIBITORS", icon: "Building2" },
      { value: "8,000+", label: "BUSINESS VISITORS", icon: "Users" },
      { value: "150+", label: "SPEAKERS", icon: "Mic" },
      { value: "30+", label: "COUNTRY PARTICIPATION", icon: "Globe" },
      { value: "3", label: "DAYS OF BUSINESS", icon: "CalendarDays" },
    ],
  },
  {
    key: "participate-cta",
    name: "ParticipateCta",
    enabled: true,
    title: "READY TO CONNECT WITH THE RIGHT BUSINESSES?",
    description: "Join the Buyer–Seller Meet at Bharat Organic Expo 2027.",
    buttonLabel: "REGISTER AS A BUYER",
    buttonHref: "/registration/buyer-registration",
    secondaryButtonLabel: "BOOK YOUR STALL",
    secondaryButtonHref: "/registration/book-a-stand",
  },
];
