export const seoRoutes = [
  {
    path: "/",
    label: "Home",
    title: "Bharat Organic Expo 2027 - International Organic Trade Fair & Conference",
    description: "Bharat Organic Expo 2027 is India's premier international exhibition & conference for organic food, natural products, bio-farming, and sustainable agriculture.",
    ogImage: "https://bharatorganicexpo.com/assets/images/og-banner.png",
    keywords: ["Bharat Organic Expo", "Organic Trade Fair India", "Organic Farming Conference", "Natural Products Exhibition"],
  },
  {
    path: "/about",
    label: "About Us",
    title: "About Bharat Organic Expo 2027 - Vision & Mission",
    description: "Learn about Bharat Organic Expo 2027, bringing together organic farmers, producers, exporters, and buyers to accelerate sustainable agriculture in India.",
    ogImage: "https://bharatorganicexpo.com/assets/images/og-banner.png",
    keywords: ["About Bharat Organic", "Organic Mission India", "Organic Agriculture Exhibition"],
  },
  {
    path: "/why-exhibit",
    label: "Why Exhibit",
    title: "Why Exhibit - Bharat Organic Expo 2027",
    description: "Showcase your organic products to thousands of global buyers, distributors, retailers, and institutional leaders at Bharat Organic Expo 2027.",
    ogImage: "https://bharatorganicexpo.com/assets/images/og-banner.png",
    keywords: ["Exhibit Organic Expo", "Organic Stall Booking", "Organic Business Platform"],
  },
  {
    path: "/why-visit",
    label: "Why Visit",
    title: "Why Visit - Bharat Organic Expo 2027",
    description: "Explore thousands of certified organic products, meet top organic brands, attend expert conferences, and discover sustainable innovations.",
    ogImage: "https://bharatorganicexpo.com/assets/images/og-banner.png",
    keywords: ["Visit Organic Expo", "Organic Product Sourcing", "Organic Trade Buyers"],
  },
  {
    path: "/buyer-seller-meet",
    label: "Buyer Seller Meet",
    title: "B2B Buyer Seller Meet - Bharat Organic Expo 2027",
    description: "Participate in targeted B2B meetings between international organic buyers, domestic distributors, and certified organic producers.",
    ogImage: "https://bharatorganicexpo.com/assets/images/og-banner.png",
    keywords: ["Organic B2B Meet", "Organic Buyer Seller", "Organic Sourcing Event"],
  },
  {
    path: "/exhibition-categories",
    label: "Exhibition Categories",
    title: "Exhibition Categories - Organic Food, Farming & Wellness",
    description: "Discover wide-ranging exhibition categories including organic food & beverages, bio-fertilizers, natural cosmetics, herbal care, and sustainable packaging.",
    ogImage: "https://bharatorganicexpo.com/assets/images/og-banner.png",
    keywords: ["Organic Product Categories", "Bio-fertilizer Exhibition", "Natural Cosmetics Expo"],
  },
  {
    path: "/exhibitors",
    label: "Exhibitors List",
    title: "Exhibitors List - Bharat Organic Expo 2027",
    description: "Browse the complete list of participating organic brands, certified producers, exporters, and technology providers at Bharat Organic Expo 2027.",
    ogImage: "https://bharatorganicexpo.com/assets/images/og-banner.png",
    keywords: ["Organic Exhibitors", "Organic Brands India", "Organic Exporters List"],
  },
  {
    path: "/sponsorship",
    label: "Sponsorship Opportunities",
    title: "Sponsorship Opportunities - Bharat Organic Expo 2027",
    description: "Elevate your brand leadership through exclusive sponsorship packages at India's flagship organic trade exhibition.",
    ogImage: "https://bharatorganicexpo.com/assets/images/og-banner.png",
    keywords: ["Organic Expo Sponsorship", "Brand Partner Organic", "Trade Fair Sponsor"],
  },
  {
    path: "/partnership",
    label: "Partnership",
    title: "Partner With Us - Bharat Organic Expo 2027",
    description: "Join hands as an institutional partner, association, media partner, or industry supporter for Bharat Organic Expo 2027.",
    ogImage: "https://bharatorganicexpo.com/assets/images/og-banner.png",
    keywords: ["Organic Partnership", "Association Partner Organic", "Media Partner Expo"],
  },
  {
    path: "/registration",
    label: "Visitor Registration",
    title: "Register as Visitor - Bharat Organic Expo 2027",
    description: "Register online for fast-track entry to Bharat Organic Expo 2027. Access B2B conferences, exhibition halls, and networking zones.",
    ogImage: "https://bharatorganicexpo.com/assets/images/og-banner.png",
    keywords: ["Organic Expo Registration", "Visitor Pass Organic", "Trade Registration"],
  },
  {
    path: "/participate-as-exhibitor",
    label: "Book a Stall",
    title: "Participate as Exhibitor - Book Stall Bharat Organic Expo 2027",
    description: "Book your exhibition space at Bharat Organic Expo 2027 and showcase your organic products to thousands of decision-makers.",
    ogImage: "https://bharatorganicexpo.com/assets/images/og-banner.png",
    keywords: ["Book Stall Organic Expo", "Exhibitor Registration", "Organic Booth Booking"],
  },
  {
    path: "/blog",
    label: "Blog & News",
    title: "Organic Industry Insights & News - Bharat Organic Expo",
    description: "Read latest insights, market trends, certification guides, and news from the global and Indian organic agriculture industry.",
    ogImage: "https://bharatorganicexpo.com/assets/images/og-banner.png",
    keywords: ["Organic Industry Blog", "Organic Farming Trends", "Organic Certification News"],
  },
  {
    path: "/careers",
    label: "Careers",
    title: "Careers & Job Opportunities - Bharat Organic Expo",
    description: "Join our team and build a rewarding career in organic event management, trade fair coordination, and sustainable agriculture outreach.",
    ogImage: "https://bharatorganicexpo.com/assets/images/og-banner.png",
    keywords: ["Organic Careers", "Event Management Jobs", "Agriculture Expo Jobs"],
  },
  {
    path: "/contact",
    label: "Contact Us",
    title: "Contact Bharat Organic Expo 2027 Team",
    description: "Get in touch with the Bharat Organic Expo team for stall booking, visitor queries, sponsorship, and media inquiries.",
    ogImage: "https://bharatorganicexpo.com/assets/images/og-banner.png",
    keywords: ["Contact Organic Expo", "Stall Inquiry", "Expo Helpline"],
  },
  {
    path: "/feedback",
    label: "Feedback",
    title: "Share Your Feedback - Bharat Organic Expo",
    description: "Share your valuable feedback and suggestions to help us make Bharat Organic Expo better.",
    ogImage: "https://bharatorganicexpo.com/assets/images/og-banner.png",
    keywords: ["Expo Feedback", "Visitor Feedback"],
  },
];

export const pageKeyToPathMap: Record<string, string> = {
  landing: "/",
  about: "/about",
  "why-exhibit": "/why-exhibit",
  "why-visit": "/why-visit",
  "buyer-seller-meet": "/buyer-seller-meet",
  "exhibition-categories": "/exhibition-categories",
  exhibitors: "/exhibitors",
  sponsorship: "/sponsorship",
  partnership: "/partnership",
  registration: "/registration",
  "participate-as-exhibitor": "/participate-as-exhibitor",
  blog: "/blog",
  careers: "/careers",
  contact: "/contact",
  feedback: "/feedback",
};

export function getFallbackSeo(pageKey: string) {
  const path = pageKeyToPathMap[pageKey];
  const route = seoRoutes.find(r => r.path === path);
  if (!route) return null;
  
  return {
    metaTitle: route.title,
    metaDescription: route.description,
    metaKeywords: route.keywords.join(", "),
    ogTitle: route.title,
    ogDescription: route.description,
    ogImage: route.ogImage,
    canonicalUrl: `https://bharatorganicexpo.com${route.path}`,
    breadcrumbName: route.label,
  };
}
