import { LandingSectionContent } from "./landingContent";

export const defaultWhyExhibitSections: LandingSectionContent[] = [
  {
    key: "why-exhibit-hero",
    name: "HeroSection",
    enabled: true,
    eyebrow: "INDIA'S PREMIER ORGANIC & WELLNESS EVENT",
    titlePrimary: "CONNECT. COLLABORATE.",
    titleSecondary: "CULTIVATE A HEALTHIER TOMORROW.",
    description: "Bharat Organic Expo brings together global innovators, brands, buyers & experts to promote sustainable living and natural well-being.",
    buttonLabel: "Book Your Stall",
    buttonHref: "/registration/book-a-stand",
    secondaryButtonLabel: "Download Brochure",
    secondaryButtonHref: "/download/invited card.pdf",
    bgImage: "",
    items: [
      { main: "Global", sub: "Exposure", image: "/uploads/icons/x1.png" },
      { main: "Quality", sub: "Connections", image: "/uploads/icons/x2.png" },
      { main: "Business", sub: "Growth", image: "/uploads/icons/x3.png" },
      { main: "Brand", sub: "Visibility", image: "/uploads/icons/x4.png" },
    ],
  },
  {
    key: "exhibitors-stats",
    name: "StatsBand",
    enabled: true,
    title: "EXPECTED IMPACT",
    items: [
      { val: "8,000+", label: "VISITORS / DELEGATES", icon: "Users" },
      { val: "200+", label: "EXHIBITORS", icon: "Building2" },
      { val: "1,000+", label: "GLOBAL BUYERS", icon: "Globe" },
      { val: "65+", label: "EXPERT SPEAKERS", icon: "Mic" },
      { val: "B2B", label: "MEETINGS", icon: "Handshake" },
    ],
  },
  {
    key: "reasons-to-exhibit",
    name: "ReasonsSection",
    enabled: true,
    title: "Top Reasons to Exhibit at Bharat Organic Expo 2027",
    items: [
      {
        title1: "GLOBAL",
        title2: "BUYER ACCESS",
        description: "Meet thousands of qualified buyers, importers, distributors and decision-makers from around the world.",
        image: "/uploads/icons/11og.webp",
        feature1: "Access new global markets",
        feature2: "Connect with key buyers",
        feature3: "Increase international reach",
        features: ["Access new global markets", "Connect with key buyers", "Increase international reach"],
      },
      {
        title1: "MAXIMUM BRAND",
        title2: "VISIBILITY",
        description: "Showcase your brand to a highly targeted audience and stand out in the competitive market.",
        image: "/uploads/icons/12og.webp",
        feature1: "High brand recall",
        feature2: "Media & PR exposure",
        feature3: "Digital promotions",
        features: ["High brand recall", "Media & PR exposure", "Digital promotions"],
      },
      {
        title1: "EXPAND YOUR",
        title2: "NETWORK",
        description: "Build valuable connections with industry leaders, partners and potential collaborators.",
        image: "/uploads/icons/13og.webp",
        feature1: "New partnerships",
        feature2: "Business alliances",
        feature3: "Long-term relationships",
        features: ["New partnerships", "Business alliances", "Long-term relationships"],
      },
      {
        title1: "LAUNCH & SHOWCASE",
        title2: "INNOVATIONS",
        description: "Introduce new organic products, technologies and solutions to the right audience.",
        image: "/uploads/icons/14og.webp",
        feature1: "Product launches",
        feature2: "Live demonstrations",
        feature3: "Market validation",
        features: ["Product launches", "Live demonstrations", "Market validation"],
      },
      {
        title1: "B2B MATCHMAKING",
        title2: "& MEETINGS",
        description: "Pre-scheduled B2B meetings to generate quality leads and new business.",
        image: "/uploads/icons/15og.webp",
        feature1: "One-to-one meetings",
        feature2: "Targeted matchmaking",
        feature3: "Better conversions",
        features: ["One-to-one meetings", "Targeted matchmaking", "Better conversions"],
      },
      {
        title1: "BOOST SALES &",
        title2: "BUSINESS GROWTH",
        description: "Explore new markets, increase exports and drive long-term business growth.",
        image: "/uploads/icons/i6.png",
        feature1: "Increase revenue",
        feature2: "Expand customer base",
        feature3: "Sustainable growth",
        features: ["Increase revenue", "Expand customer base", "Sustainable growth"],
      },
    ],
  },
  {
    key: "industries-section",
    name: "IndustriesSection",
    enabled: true,
    title: "Industries We Serve",
    items: [
      {
        title: "Organic Food & Beverages",
        description: "Wide range of certified organic foods, beverages, healthy snacks, grains, pulses, and ingredients.",
        image: "",
      },
      {
        title: "AYUSH, Ayurveda & Herba",
        description: "Ayurvedic medicines, herbal supplements, essential oils, teas, wellness products and holistic solutions.",
        image: "",
      },
      {
        title: "Organic Natural Farming",
        description: "Natural farming practices, organic cultivation methods, innovations and farm-to-market solutions.",
        image: "",
      },
      {
        title: "Organic Inputs, Seeds & Bio- Inputs",
        description: "Bio-fertilisers, organic manures, soil enhancers, pesticides and high-quality seeds.",
        image: "",
      },
      {
        title: "Dairy, Livestock & Allied",
        description: "Organic dairy products, livestock nutrition, animal health solutions and sustainable practices.",
        image: "",
      },
      {
        title: "Natural Beauty & Personal Care",
        description: "Herbal skincare, haircare, personal care and eco-friendly beauty products.",
        image: "",
      },
      {
        title: "Nutraceuticals & Functional Nutrition",
        description: "Dietary supplements, functional foods, immunity boosters and wellness nutrition products.",
        image: "",
      },
      {
        title: "Sustainable Packaging & Processing",
        description: "Eco-friendly, biodegradable, recyclable and sustainable packaging solutions.",
        image: "",
      },
      {
        title: "AgriTech, GreenTech & Innovation",
        description: "Innovative agri technologies, smart farming, irrigation, farm mechanization and digital solutions.",
        image: "",
      },
      {
        title: "Certification, Export, Trade & Services",
        description: "Exporters, importers, trade associations and global business opportunities for organic products.",
        image: "",
      },
    ],
  },
  {
    key: "buyers-section",
    name: "BuyersSection",
    enabled: true,
    title: "WHO SHOULD ATTEND?",
    subtitle: "Qualified Buyers & Industry Delegates",
    description: "Meet decision-makers actively sourcing certified organic and sustainable products.",
    buttonLabel: "Book Your Stall",
    buttonHref: "/registration/book-a-stand",
    items: [
      { title: "Hospitals, Clinics & Healthcare Providers" },
      { title: "Importers, Exporters & Distributors" },
      { title: "Pharmacies & Retail Chains" },
      { title: "Wellness Centres & Spa Chains" },
      { title: "E-commerce & Online Retailers" },
      { title: "Government & Institutional Buyers" },
      { title: "Investors & Business Partners" },
      { title: "Researchers & Academicians" },
    ],
  },
  {
    key: "testimonials-section",
    name: "TestimonialsSection",
    enabled: true,
    title: "What Our Exhibitors Say",
  },
];

