import { LandingSectionContent } from "./landingContent";

export const defaultWhyExhibitSections: LandingSectionContent[] = [
  {
    key: "why-exhibit-hero",
    name: "HeroSection",
    enabled: true,
    eyebrow: "INDIA'S PREMIER ORGANIC & WELLNESS EVENT",
    titlePrimary: "CONNECT. COLLABORATE.",
    titleSecondary: "CULTIVATE A HEALTHIER TOMORROW.",
    description: "Bharat Organic Expo brings together global innovators, brands, buyers & experts to promote sustainable living and natural well-being.",
    buttonLabel: "Book Your Stall",
    buttonHref: "/registration/book-a-stand",
    secondaryButtonLabel: "Download Brochure",
    secondaryButtonHref: "/download/invited card.pdf",
    date: "19 – 21 FEBRUARY 2027",
    location: "BHARAT MANDAPAM, NEW DELHI, INDIA",
    items: [
      { main: "Global", sub: "Exposure", icon: "Globe" },
      { main: "Quality", sub: "Connections", icon: "ShieldCheck" },
      { main: "Business", sub: "Growth", icon: "TrendingUp" },
      { main: "Brand", sub: "Visibility", icon: "Megaphone" },
    ],
  },
  {
    key: "exhibitors-stats",
    name: "StatsBand",
    enabled: true,
    title: "EXPECTED IMPACT",
    items: [
      { val: "8,000+", label: "VISITORS / DELEGATES", icon: "Users" },
      { val: "200+", label: "EXHIBITORS", icon: "Building2" },
      { val: "1,000+", label: "GLOBAL BUYERS", icon: "Globe" },
      { val: "65+", label: "EXPERT SPEAKERS", icon: "Mic" },
      { val: "B2B", label: "MEETINGS", icon: "Handshake" },
    ],
  },
  {
    key: "reasons-to-exhibit",
    name: "ReasonsSection",
    enabled: true,
    title: "Top Reasons to Exhibit at Bharat Organic Expo 2027",
    items: [
      {
        title1: "GLOBAL",
        title2: "BUYER ACCESS",
        description: "Meet thousands of qualified buyers, importers, distributors and decision-makers from around the world.",
        features: ["Access new global markets", "Connect with key buyers", "Increase international reach"],
      },
      {
        title1: "MAXIMUM BRAND",
        title2: "VISIBILITY",
        description: "Showcase your brand to a highly targeted audience and stand out in the competitive market.",
        features: ["High brand recall", "Media & PR exposure", "Digital promotions"],
      },
      {
        title1: "EXPAND YOUR",
        title2: "NETWORK",
        description: "Build valuable connections with industry leaders, partners and potential collaborators.",
        features: ["New partnerships", "Business alliances", "Long-term relationships"],
      },
      {
        title1: "LAUNCH & SHOWCASE",
        title2: "INNOVATIONS",
        description: "Introduce new organic products, technologies and solutions to the right audience.",
        features: ["Product launches", "Live demonstrations", "Market validation"],
      },
      {
        title1: "B2B MATCHMAKING",
        title2: "& MEETINGS",
        description: "Pre-scheduled B2B meetings to generate quality leads and new business.",
        features: ["One-to-one meetings", "Targeted matchmaking", "Better conversions"],
      },
      {
        title1: "BOOST SALES &",
        title2: "BUSINESS GROWTH",
        description: "Explore new markets, increase exports and drive long-term business growth.",
        features: ["Increase revenue", "Expand customer base", "Sustainable growth"],
      },
    ],
  },
  {
    key: "industries-section",
    name: "IndustriesSection",
    enabled: true,
    title: "Industries We Serve",
    subtitle: "Explore Diverse Exhibition Sectors",
    description: "One Platform. Every Opportunity. Bharat Organic Expo brings together the entire organic ecosystem under one roof. Explore a wide range of sectors driving sustainable living, natural wellness, ethical production and global trade.",
    items: [
      {
        title: "Organic Food & Beverages",
        desc: "Wide range of certified organic foods, beverages, healthy snacks, grains, pulses, and ingredients.",
        icon: "Apple",
      },
      {
        title: "AYUSH, Ayurveda & Herba",
        desc: "Ayurvedic medicines, herbal supplements, essential oils, teas, wellness products and holistic solutions.",
        icon: "Leaf",
      },
      {
        title: "Organic Natural Farming",
        desc: "Natural farming practices, organic cultivation methods, innovations and farm-to-market solutions.",
        icon: "Sprout",
      },
      {
        title: "Organic Inputs, Seeds & Bio- Inputs",
        desc: "Bio-fertilisers, organic manures, soil enhancers, pesticides and high-quality seeds.",
        icon: "Package",
      },
      {
        title: "Dairy, Livestock & Allied",
        desc: "Organic dairy products, livestock nutrition, animal health solutions and sustainable practices.",
        icon: "Milk",
      },
      {
        title: "Natural Beauty & Personal Care",
        desc: "Herbal skincare, haircare, personal care and eco-friendly beauty products.",
        icon: "Droplet",
      },
      {
        title: "Nutraceuticals & Functional Nutrition",
        desc: "Dietary supplements, functional foods, immunity boosters and wellness nutrition products.",
        icon: "Pill",
      },
      {
        title: "Sustainable Packaging & Processing",
        desc: "Eco-friendly, biodegradable, recyclable and sustainable packaging solutions.",
        icon: "Box",
      },
      {
        title: "AgriTech, GreenTech & Innovation",
        desc: "Innovative agri technologies, smart farming, irrigation, farm mechanization and digital solutions.",
        icon: "Tractor",
      },
      {
        title: "Certification, Export, Trade & Services",
        desc: "Exporters, importers, trade associations and global business opportunities for organic products.",
        icon: "Globe",
      },
    ],
  },
  {
    key: "buyers-section",
    name: "BuyersSection",
    enabled: true,
    title: "WHO SHOULD ATTEND?",
    subtitle: "Qualified Buyers & Industry Delegates",
    description: "Meet decision-makers actively sourcing certified organic and sustainable products.",
    buttonLabel: "Book Your Stall",
    buttonHref: "/registration/book-a-stand",
    items: [
      { title: "Hospitals, Clinics & Healthcare Providers" },
      { title: "Importers, Exporters & Distributors" },
      { title: "Pharmacies & Retail Chains" },
      { title: "Wellness Centres & Spa Chains" },
      { title: "E-commerce & Online Retailers" },
      { title: "Government & Institutional Buyers" },
      { title: "Investors & Business Partners" },
      { title: "Researchers & Academicians" },
    ],
  },
  {
    key: "testimonials-section",
    name: "TestimonialsSection",
    enabled: true,
    title: "What Our Exhibitors Say",
    subtitle: "What Past Exhibitors Say",
    items: [
      {
        companyName1: "Green Earth Organics Pvt. Ltd.",
        companyName2: "Organic Food & Agri",
        location: "Mumbai, India",
        quote: "Bharat Organic Expo gave us direct access to 500+ qualified buyers in just 3 days. We signed 12 new distribution agreements and expanded our reach to Southeast Asia. A must-attend event for any organic food brand!",
        initials: "GE",
      },
      {
        companyName1: "NatureFarm Exports",
        companyName2: "Agriculture & Exports",
        location: "Pune, India",
        quote: "The B2B matchmaking sessions were incredibly productive. We met international importers we would never have connected with otherwise. Our export revenue grew 40% after the expo.",
        initials: "NF",
      },
      {
        companyName1: "Herbal Heritage India",
        companyName2: "Ayush & Herbal Products",
        location: "Delhi, India",
        quote: "Outstanding platform for herbal and wellness brands. The quality of visitors and their genuine interest in organic products made every conversation meaningful. Already registered for next year!",
        initials: "HH",
      },
      {
        companyName1: "PureGrow Technologies",
        companyName2: "Sustainable Agri-Tech",
        location: "Bengaluru, India",
        quote: "As a new startup, this expo gave us the visibility and credibility we needed. We connected with 3 major investors and received 200+ serious inquiries for our bio-inputs during the event.",
        initials: "PG",
      },
      {
        companyName1: "Vedic Wellness Corp",
        companyName2: "Natural Personal Care",
        location: "Jaipur, India",
        quote: "The expo exceeded all our expectations. The footfall was exceptional and the profile of visitors — distributors, retailers, and exporters — was exactly our target audience. Brilliant ROI!",
        initials: "VW",
      },
      {
        companyName1: "OrganicIndia Solutions",
        companyName2: "Certification & Compliance",
        location: "Hyderabad, India",
        quote: "We launched our new organic certification services at this expo and got 80+ inquiries on day one itself. The event team was professional and supportive throughout.",
        initials: "OI",
      },
    ],
  },
];

