import { LandingSectionContent } from "./landingContent";

export const defaultWhyVisitSections: LandingSectionContent[] = [
  {
    key: "why-visit-hero",
    name: "HeroSection",
    enabled: true,
    eyebrow: "WHY VISIT BHARAT ORGANIC EXPO 2027",
    titlePrimary: "Source Better.",
    titleSecondary: "Connect Directly.",
    titleHighlight: "Grow Your Business.",
    description: "Discover new products, meet manufacturers and suppliers, explore sourcing opportunities and build valuable business connections across India's growing organic, natural and sustainable ecosystem.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165233/moksha-sewa/assets/km.jpg",
    imageAlt: "Why Visit Bharat Organic Expo 2027",
    buttonLabel: "REGISTER AS A BUYER",
    buttonHref: "/registration/buyer-registration",
    secondaryButtonLabel: "REGISTER AS A VISITOR",
    secondaryButtonHref: "/registration/visitor-registration",
    items: [
      { value: "8,000+", label: "VISITORS / DELEGATES", icon: "Users" },
      { value: "200+", label: "EXHIBITORS", icon: "Building2" },
      { value: "GLOBAL", label: "PERSPECTIVES", icon: "Globe" },
      { value: "100+", label: "EXPERT SPEAKERS", icon: "Mic" },
      { value: "B2B", label: "MEETINGS", icon: "Handshake" },
    ],
  },
  {
    key: "why-visit-matters",
    name: "WhyVisitMatters",
    enabled: true,
    eyebrow: "BUSINESS OPPORTUNITIES UNDER ONE ROOF",
    title: "Why Your Visit Matters",
    subtitle: "Bharat Organic Expo brings the right products, suppliers and decision-makers together,",
    description: "creating real opportunities for your business growth.",
    lowerTitle: "One Visit. Multiple Opportunities.",
    lowerDescription: "Save time, meet the right people and take your business to the next level.",
    items: [
      { num: "01", title: "Discover New Products", description: "Explore a wide range of new launches, innovative products and emerging brands across multiple categories." },
      { num: "02", title: "Meet Manufacturers", description: "Connect directly with verified manufacturers, producers and suppliers from across India and beyond." },
      { num: "03", title: "Source for Your Business", description: "Find the right products for retail, distribution, e-commerce, hospitality, institutional procurement and more." },
      { num: "04", title: "Explore Private Label", description: "Meet brands and manufacturers offering OEM, contract manufacturing and private-label opportunities." },
      { num: "05", title: "Build Partnerships", description: "Explore dealership, distributorship, collaboration and long-term business partnership opportunities." },
      { num: "06", title: "Understand Market Trends", description: "Gain insights into market trends, consumer demand, industry innovations and future business opportunities." },
    ],
  },
  {
    key: "who-should-visit",
    name: "WhoShouldVisit",
    enabled: true,
    eyebrow: "ONE PLATFORM. UNLIMITED OPPORTUNITIES.",
    titlePrimary: "WHO SHOULD",
    titleSecondary: "VISIT & BENEFIT?",
    description: "Bharat Organic Expo brings together a diverse ecosystem of industry leaders, innovators, buyers, and sustainable farming pioneers driving India’s organic revolution.",
    lowerTitle: "BE PART OF INDIA’S ORGANIC MOVEMENT!",
    lowerDescription: "Connect. Collaborate. Innovate. Grow. The future is organic. Let’s build it together.",
    buttonLabel: "JOIN THE MOVEMENT. CREATE A BETTER TOMORROW.",
    buttonHref: "/registration/visitor-registration",
    items: [
      { title: "BUSINESSES & ENTREPRENEURS", description: "Manufacturers, suppliers, brand owners, exporters and startups looking to expand market reach, launch new products or source premium organic ingredients." },
      { title: "DISTRIBUTORS & RETAILERS", description: "Wholesalers, importers, retail chains, supermarkets and e-commerce buyers seeking certified organic products, exclusive partnerships and profitable trade deals." },
      { title: "ORGANIC FARMERS & PRODUCERS", description: "Farmers, FPOs, agricultural cooperatives and producers looking for high-yield organic inputs, modern agri-tech, direct buyer linkages and value addition solutions." },
      { title: "HEALTH & WELLNESS PROFESSIONALS", description: "Nutritionists, dietitians, ayurvedic practitioners, wellness experts and health therapists exploring authentic natural, herbal and organic wellness solutions." },
      { title: "INVESTORS & POLICY MAKERS", description: "Venture capitalists, angel investors, policy makers, government officials and advisors keen to back sustainable green ventures and strengthen the ecosystem." },
      { title: "MEDIA & CONTENT CREATORS", description: "Journalists, bloggers, digital content creators and influencers covering emerging sustainable organic trends, innovations and inspiring success stories." },
    ],
  },
  {
    key: "industry-segments",
    name: "IndustrySegments",
    enabled: true,
    eyebrow: "WHAT CAN YOU SOURCE?",
    subtitle: "ONE EXPO • COMPLETE ECOSYSTEM",
    title: "Explore 6 Major Industry Segments",
    buttonLabel: "EXPLORE EXHIBITOR PROFILE",
    buttonHref: "/exhibitors",
    items: [
      { num: "01", title: "Organic Food & Nutrition", subtitle: "Food • Beverages • Nutraceuticals", description: "Certified organic pulses, grains, superfoods, organic tea/coffee, cold-pressed oils & health supplements." },
      { num: "02", title: "AYUSH, Herbal & Wellness", subtitle: "Ayurveda • Herbal • Wellness", description: "Ayurvedic formulations, herbal extracts, essential oils, wellness teas & traditional remedies." },
      { num: "03", title: "Organic Agriculture", subtitle: "Farming • Seeds • Bio-Inputs", description: "Bio-fertilizers, organic pesticides, non-GMO seeds, farm machinery & organic soil enhancers." },
      { num: "04", title: "Natural Living & Personal Care", subtitle: "Beauty • Personal Care • Natural Lifestyle", description: "Organic cosmetics, natural skincare, sustainable apparel, eco-friendly home care & hygiene products." },
      { num: "05", title: "GreenTech & Sustainability", subtitle: "AgriTech • Packaging • Processing", description: "Biodegradable packaging, solar energy solutions, waste management & smart AgriTech innovations." },
      { num: "06", title: "Trade, Certification & Global Business", subtitle: "Certification • Export • Import • Business Services", description: "Organic certification bodies, export-import agencies, testing labs & B2B logistics services." },
    ],
  },
  {
    key: "buyer-seller-meet",
    name: "BuyerSellerMeetSection",
    enabled: true,
    eyebrow: "REASON TO VISIT",
    title: "Buyer–Seller Meet",
    subtitle: "MEET. CONNECT. GROW.",
    description: "A focused platform to connect serious buyers with trusted exhibitors and build long-term business relationships.",
    buttonLabel: "REGISTER AS BUYER",
    buttonHref: "/registration/buyer-registration",
    secondaryButtonLabel: "PLAN YOUR VISIT NOW",
    secondaryButtonHref: "/registration/visitor-registration",
    date: "19–21 FEBRUARY 2027",
    location: "HALL 12, BHARAT MANDAPAM, NEW DELHI",
    items: [
      { title: "Pre-scheduled Meetings", description: "We connect you with relevant exhibitors before the expo." },
      { title: "Quality Connections", description: "Meet verified manufacturers, suppliers & brands." },
      { title: "Save Time, Close Deals", description: "One-to-one meetings that help you discover, compare & decide." },
      { title: "Grow Your Business", description: "Explore new products, expand your portfolio & increase margins." },
    ],
  },
  {
    key: "awards-health-camp",
    name: "AwardsHealthCamp",
    enabled: true,
    eyebrow: "VALUE BEYOND BUSINESS",
    title: "AWARDS & RECOGNITION",
    subtitle: "CELEBRATING EXCELLENCE. INSPIRING IMPACT.",
    description: "Honouring innovation, leadership and impactful contributions that are shaping a healthier, sustainable and organic future.",
    items: [
      { title: "Recognizing Excellence", description: "Celebrate outstanding achievements across the organic ecosystem." },
      { title: "Inspiring Innovation", description: "Encouraging new ideas and solutions for a sustainable future." },
      { title: "Building Credibility", description: "Gain industry recognition and strengthen your brand value." },
      { title: "Wider Visibility", description: "Showcase your success to a global audience of buyers and leaders." },
      { title: "Driving Impact", description: "Inspire meaningful change and contribute to a better, healthier world." },
    ],
  },
  {
    key: "need-help-support",
    name: "NeedHelpSupport",
    enabled: true,
    eyebrow: "WE’RE HERE TO SUPPORT YOU",
    title: "NEED HELP?",
    description: "Our dedicated team is ready to assist you at every step of your PMS application journey.",
    lowerTitle: "OUR COMMITMENT",
    lowerDescription: "Transparent guidance. Timely support. Stronger together for a sustainable future.",
    buttonLabel: "START YOUR APPLICATION",
    buttonHref: "/registration/book-a-stand",
    contactEmail: "info@namogangewellness.com",
    phoneNumber: "+91-9654900525",
    websiteUrl: "www.bharatorganicexpo.com",
    items: [
      { title: "Email Us", subtitle: "info@namogangewellness.com", description: "We typically reply within 24 hours." },
      { title: "Call Us", subtitle: "+91-9654900525", description: "Mon – Sat 10:00 AM – 6:00 PM" },
      { title: "WhatsApp", subtitle: "+91-9654900525", description: "Quick responses during working hours." },
      { title: "Visit Website", subtitle: "www.bharatorganicexpo.com", description: "Explore PMS details, guidelines & more." },
    ],
  },
];
