"use client";

import React from "react";
import { Key } from "lucide-react";

function SectionCard({ title, icon, children, note }: { title: string; icon: React.ReactNode; children: React.ReactNode; note?: string }) {
  return (
    <div className="rounded-2xl border border-slate-700/80 bg-[#1e293b] p-6 shadow-xl">
      <div className="flex items-center gap-3 mb-3 border-b border-slate-700/70 pb-3">
        <div className="p-2 rounded-xl bg-pink-500/20 text-pink-400 border border-pink-500/40">
          {icon}
        </div>
        <div>
          <h4 className="text-[15px] font-bold text-white tracking-wide">{title}</h4>
          {note && <p className="text-[11.5px] text-slate-300 mt-0.5">{note}</p>}
        </div>
      </div>
      {children}
    </div>
  );
}

export default function AuditKeywordsSection({ page }: { page: any }) {
  if (!page) return null;

  return (
    <section id="section-keywords" className="scroll-mt-36 space-y-5">
      <div className="flex items-center justify-between border-b border-slate-700 pb-3">
        <div className="flex items-center gap-3">
          <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-pink-500 text-[12px] font-black text-slate-950 shadow-md">
            04
          </span>
          <h3 className="text-[17px] font-extrabold tracking-wide text-white uppercase">Keyword Density & Placement</h3>
        </div>
        <span className="text-[11.5px] font-bold text-pink-300 bg-pink-950/80 border border-pink-700/80 px-3.5 py-1 rounded-full">
          Content Keyword Audit
        </span>
      </div>

      <SectionCard
        title="Target Keyword Placement Matrix"
        icon={<Key className="w-5 h-5" />}
        note="Counts are measured in crawled page content. Search Console queries and configured targets are never generated by AI."
      >
        {!page?.keywordAnalysis?.available ? (
          <div className="rounded-xl border border-slate-700 bg-slate-900/80 p-5 text-[13px] leading-relaxed text-slate-300">
            <p className="font-extrabold text-white text-[14px]">Page Audited — No target keyword configured yet.</p>
            <p className="mt-1 text-slate-300">
              This section needs a configured target keyword for this URL or a matching Search Console query. Technical,
              content, link and metadata checks still ran normally.
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto rounded-xl border border-slate-700 bg-slate-900/90">
            <table className="w-full min-w-[760px] text-[13px]">
              <thead className="bg-slate-800 border-b border-slate-700 text-slate-200">
                <tr>
                  <th className="py-2.5 px-4 text-left font-extrabold">Keyword</th>
                  <th className="px-3 text-center font-extrabold">Source</th>
                  <th className="px-2 text-center font-extrabold">Title</th>
                  <th className="px-2 text-center font-extrabold">Meta</th>
                  <th className="px-2 text-center font-extrabold">H1</th>
                  <th className="px-2 text-center font-extrabold">H2/H3</th>
                  <th className="px-2 text-center font-extrabold">Opening</th>
                  <th className="px-4 text-right font-extrabold">Mentions</th>
                  <th className="px-4 text-right font-extrabold">Density</th>
                </tr>
              </thead>
              <tbody>
                {page.keywordAnalysis.targets.map((target: any, idx: number) => (
                  <tr key={`${target.source}-${target.keyword}`} className={`border-b border-slate-800 hover:bg-slate-800/80 ${idx % 2 === 0 ? "bg-slate-900/50" : ""}`}>
                    <td className="py-2.5 px-4 font-black text-white">{target.keyword}</td>
                    <td className="px-3 text-center capitalize text-slate-300 font-medium text-[11.5px]">
                      {target.source.replaceAll("_", " ")}
                    </td>
                    {[
                      target.presentInTitle,
                      target.presentInMetaDescription,
                      target.presentInH1,
                      target.presentInHeadings,
                      target.presentInOpeningContent,
                    ].map((present, index) => (
                      <td key={index} className="text-center font-medium">
                        {present ? (
                          <span className="inline-flex h-5.5 w-5.5 items-center justify-center rounded-full bg-emerald-500/30 text-emerald-300 font-black text-[12px] border border-emerald-500/50">✓</span>
                        ) : (
                          <span className="text-slate-500 font-bold text-[12px]">✕</span>
                        )}
                      </td>
                    ))}
                    <td className="px-4 text-right tabular-nums font-extrabold text-white">{target.exactMentions}</td>
                    <td className="px-4 text-right tabular-nums text-pink-400 font-black">
                      {target.densityPercent.toFixed(2)}%
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </SectionCard>
    </section>
  );
}
